from collections import Counter


CATEGORY_ORDER = ['Génie logiciel',
 'Java',
 'Spring / Spring Boot',
 'SQL / Bases de données',
 'Développement Web',
 'Algorithmes et structures de données']
DIFFICULTY_ORDER = ['Basique', 'Intermédiaire', 'Avancé']
CATEGORY_PREFIXES = {'Génie logiciel': 'GL',
 'Java': 'JAVA',
 'Spring / Spring Boot': 'SPR',
 'SQL / Bases de données': 'SQL',
 'Développement Web': 'WEB',
 'Algorithmes et structures de données': 'ALGO'}
DIFFICULTY_TARGETS = {'Basique': 38, 'Intermédiaire': 43, 'Avancé': 27}


def q(category, difficulty, statement, options, answer, explanation):
    if len(options) != 4:
        raise ValueError(f"Chaque question doit avoir 4 choix: {statement}")
    if answer not in {"A", "B", "C", "D"}:
        raise ValueError(f"Réponse invalide pour: {statement}")
    return {
        "category": category,
        "difficulty": difficulty,
        "statement": statement,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }


SEED_QUESTIONS = [{'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': 'Quel modèle de cycle de vie suit généralement des phases séquentielles comme analyse, conception, '
               'développement et test ?',
  'options': ['Scrum', 'Waterfall', 'Kanban', 'DevOps'],
  'answer': 'B',
  'explanation': 'Le modèle Waterfall organise le projet en étapes successives avec peu de retours en arrière.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': 'Que représente UML ?',
  'options': ['Un langage de modélisation unifié',
              "Un moteur d'exécution Java",
              'Une base de données relationnelle',
              'Un outil de versionnement'],
  'answer': 'A',
  'explanation': "UML signifie Unified Modeling Language et sert à modéliser la structure et le comportement d'un "
                 'système.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': 'Quel rôle principal joue Scrum Master dans Scrum ?',
  'options': ['Déployer en production',
              "Supprimer les obstacles pour l'équipe",
              'Valider tout le code',
              'Écrire la documentation utilisateur'],
  'answer': 'B',
  'explanation': "Le Scrum Master facilite le processus Scrum et aide l'équipe à lever les blocages."},
 {'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': 'Quel diagramme UML est le plus utilisé pour représenter les classes et leurs relations ?',
  'options': ['Diagramme de séquence', "Diagramme d'états", 'Diagramme de classes', 'Diagramme de déploiement'],
  'answer': 'C',
  'explanation': 'Le diagramme de classes montre les attributs, méthodes et relations entre classes.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': "Quel principe SOLID recommande qu'une classe n'ait qu'une seule raison de changer ?",
  'options': ['Single Responsibility Principle',
              'Open/Closed Principle',
              'Liskov Substitution Principle',
              'Dependency Inversion Principle'],
  'answer': 'A',
  'explanation': 'Le SRP impose une responsabilité principale unique par classe.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Basique',
  'statement': "Quel design pattern garantit qu'une classe ne possède qu'une seule instance ?",
  'options': ['Factory', 'Observer', 'Singleton', 'Strategy'],
  'answer': 'C',
  'explanation': "Singleton contrôle l'instanciation pour ne fournir qu'une unique instance."},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': 'Dans un diagramme de séquence UML, que représente une flèche entre deux objets ?',
  'options': ['Un héritage', 'Un message échangé', 'Une clé étrangère', 'Un package'],
  'answer': 'B',
  'explanation': "Le diagramme de séquence met en évidence les messages échangés dans l'ordre temporel."},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel avantage principal apporte le pattern Factory ?',
  'options': ['Empêcher les exceptions',
              "Centraliser la création d'objets",
              'Éviter les tests unitaires',
              'Réduire la mémoire JVM'],
  'answer': 'B',
  'explanation': "Factory encapsule l'instanciation et limite le couplage avec les implémentations concrètes."},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': 'Le TDD suit généralement quel enchaînement ?',
  'options': ['Code, build, release', 'Red, Green, Refactor', 'Design, test, merge', 'Plan, code, delete'],
  'answer': 'B',
  'explanation': "En TDD, on écrit d'abord un test en échec, on fait passer le test, puis on refactorise."},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel énoncé décrit le mieux le principe Open/Closed ?',
  'options': ['Une classe doit être fermée aux tests',
              "Un module doit être ouvert à l'extension et fermé à la modification",
              'Une API doit être fermée au réseau',
              'Une classe doit contenir un seul attribut public'],
  'answer': 'B',
  'explanation': 'Le principe Open/Closed vise à ajouter des comportements sans modifier le code stable existant.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': 'Que fait généralement le pattern Observer ?',
  'options': ['Il crée des threads',
              "Il notifie plusieurs abonnés lors d'un changement d'état",
              'Il applique la normalisation 3NF',
              'Il remplace Git'],
  'answer': 'B',
  'explanation': 'Observer met en place une relation sujet/observateurs avec notification automatique.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Intermédiaire',
  'statement': "Quelle commande Git crée une nouvelle branche et s'y positionne immédiatement ?",
  'options': ['git merge feature', 'git checkout -b feature', 'git reset --hard feature', 'git branch -d feature'],
  'answer': 'B',
  'explanation': '`git checkout -b feature` crée la branche puis bascule dessus en une seule commande.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': "Quel risque principal apparaît lorsqu'une équipe applique Scrum sans définition claire de 'Done' ?",
  'options': ['Le compilateur échoue systématiquement',
              'Les incréments deviennent difficiles à valider objectivement',
              'Les diagrammes UML deviennent obligatoires',
              'La branche main est supprimée'],
  'answer': 'B',
  'explanation': 'Sans Definition of Done, la qualité et la complétude des livrables ne sont pas mesurables de manière '
                 'cohérente.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': 'Lequel des cas suivants viole le plus directement le principe de substitution de Liskov ?',
  'options': ['Une sous-classe ajoute une méthode privée',
              'Une sous-classe change le contrat attendu et lève une exception pour un cas auparavant valide',
              'Une sous-classe utilise un logger',
              'Une interface possède deux implémentations'],
  'answer': 'B',
  'explanation': 'Une sous-classe ne doit pas casser les attentes fonctionnelles des clients du type parent.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': 'Quel bénéfice majeur apporte le pattern MVC dans une application riche ?',
  'options': ['Il supprime le besoin de tests',
              'Il sépare les responsabilités entre données, interface et contrôle',
              'Il remplace une base de données relationnelle',
              'Il garantit le multithreading'],
  'answer': 'B',
  'explanation': 'MVC améliore la maintenabilité en isolant modèle, vue et contrôleur.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': 'Quelle stratégie de branchement Git limite le plus les conflits de longue durée ?',
  'options': ['Conserver des branches de fonctionnalités pendant plusieurs mois',
              'Intégrer fréquemment de petites branches de courte durée',
              'Commiter uniquement en fin de sprint',
              'Travailler uniquement sur des archives ZIP'],
  'answer': 'B',
  'explanation': 'Des branches courtes et des intégrations fréquentes réduisent la divergence et les conflits.'},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': 'Dans un système fortement couplé, quel changement améliore le plus la testabilité ?',
  'options': ['Ajouter des variables globales',
              "Introduire l'inversion de dépendance avec interfaces injectées",
              'Supprimer les exceptions',
              'Remplacer toutes les classes par une seule'],
  'answer': 'B',
  'explanation': "L'inversion de dépendance permet de substituer des implémentations de test et réduit le couplage."},
 {'category': 'Génie logiciel',
  'difficulty': 'Avancé',
  'statement': "Quel indicateur traduit le mieux la valeur d'un test d'intégration ?",
  'options': ['Il vérifie le style de code',
              'Il valide la collaboration entre composants réels ou proches du réel',
              "Il garantit l'absence de bugs UX",
              'Il remplace entièrement les tests unitaires'],
  'answer': 'B',
  'explanation': "Les tests d'intégration couvrent les interactions entre modules, couches ou services."},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': "Quel concept POO permet à une classe fille de réutiliser le comportement d'une classe mère ?",
  'options': ['Encapsulation', 'Polymorphisme', 'Héritage', 'Sérialisation'],
  'answer': 'C',
  'explanation': "L'héritage permet à une classe de spécialiser une autre classe."},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': "Quelle collection Java n'autorise pas les doublons ?",
  'options': ['List', 'Set', 'ArrayList', 'LinkedList'],
  'answer': 'B',
  'explanation': "L'interface Set garantit l'unicité des éléments."},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': 'À quoi sert un bloc try-catch ?',
  'options': ['À définir une interface', 'À gérer les exceptions', 'À créer un thread', 'À compiler plus vite'],
  'answer': 'B',
  'explanation': "Le bloc try-catch intercepte et traite des exceptions pendant l'exécution."},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': 'Quelle classe est couramment utilisée pour représenter une paire clé-valeur ?',
  'options': ['List', 'Queue', 'Map', 'Stream'],
  'answer': 'C',
  'explanation': 'Map associe une clé à une valeur.'},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': "Quel mot-clé empêche la modification d'une variable locale après son initialisation ?",
  'options': ['static', 'const', 'final', 'volatile'],
  'answer': 'C',
  'explanation': '`final` interdit la réaffectation de la variable.'},
 {'category': 'Java',
  'difficulty': 'Basique',
  'statement': "Quelle méthode est appelée lorsqu'on démarre un thread via `new Thread(r).start()` ?",
  'options': ['init()', 'call()', 'run()', 'execute()'],
  'answer': 'C',
  'explanation': "`start()` crée un nouveau fil d'exécution qui invoque ensuite `run()`."},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel avantage principal offrent les generics en Java ?',
  'options': ['Ils remplacent la JVM',
              'Ils améliorent la sécurité de type à la compilation',
              'Ils permettent plusieurs héritages de classes',
              "Ils évitent tout casting à l'exécution même avec du code brut"],
  'answer': 'B',
  'explanation': 'Les generics détectent des erreurs de type à la compilation et réduisent les casts explicites.'},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': 'Que retourne `stream().filter(x -> x > 10).count()` ?',
  'options': ['Une liste filtrée',
              "Le nombre d'éléments satisfaisant la condition",
              'Le premier élément > 10',
              'Une Optional'],
  'answer': 'B',
  'explanation': "`count()` renvoie le nombre d'éléments du flux après filtrage."},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': 'Quand utilise-t-on principalement `Optional` ?',
  'options': ['Pour gérer explicitement une valeur potentiellement absente',
              'Pour remplacer toutes les collections',
              'Pour créer des threads daemon',
              'Pour définir une exception vérifiée'],
  'answer': 'A',
  'explanation': "Optional explicite l'absence éventuelle d'une valeur et limite certains `NullPointerException`."},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': "Quel type d'exception doit être déclarée ou capturée si elle est checked ?",
  'options': ['RuntimeException', 'NullPointerException', 'IOException', 'ArithmeticException'],
  'answer': 'C',
  'explanation': '`IOException` est une checked exception : elle doit être traitée ou déclarée.'},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel composant JDBC représente généralement une requête SQL paramétrée précompilée ?',
  'options': ['DriverManager', 'PreparedStatement', 'ResultSetMetaData', 'SQLException'],
  'answer': 'B',
  'explanation': "PreparedStatement permet de paramétrer la requête et aide à prévenir l'injection SQL."},
 {'category': 'Java',
  'difficulty': 'Intermédiaire',
  'statement': 'Quelle différence majeure existe entre `ArrayList` et `LinkedList` ?',
  'options': ['ArrayList interdit les null',
              "LinkedList optimise mieux les insertions/suppressions au milieu mais pas l'accès indexé",
              'ArrayList implémente Set',
              "LinkedList n'est pas une List"],
  'answer': 'B',
  'explanation': "ArrayList favorise l'accès indexé, alors que LinkedList favorise certaines insertions/suppressions."},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': 'Quel effet a le mot-clé `volatile` sur un champ partagé entre threads ?',
  'options': ['Il rend toutes les opérations atomiques',
              'Il garantit surtout la visibilité des écritures entre threads',
              'Il empêche tout blocage',
              'Il remplace `synchronized` dans tous les cas'],
  'answer': 'B',
  'explanation': "`volatile` garantit la visibilité mémoire, mais pas l'atomicité d'opérations composées comme "
                 '`count++`.'},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': 'Pourquoi préférer `ExecutorService` à la création manuelle de nombreux threads ?',
  'options': ["Parce qu'il empêche les exceptions",
              "Parce qu'il gère un pool de threads et le cycle de vie des tâches",
              "Parce qu'il compile le code plus vite",
              "Parce qu'il remplace les interfaces fonctionnelles"],
  'answer': 'B',
  'explanation': "ExecutorService mutualise les threads et facilite la gestion, la limitation et l'arrêt des tâches."},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': 'Quel est le rôle principal du garbage collector de la JVM ?',
  'options': ['Optimiser les index SQL',
              'Libérer automatiquement la mémoire des objets non référencés',
              'Empêcher les exceptions vérifiées',
              'Compiler les fichiers XML'],
  'answer': 'B',
  'explanation': 'Le garbage collector récupère la mémoire des objets qui ne sont plus atteignables.'},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': 'Dans une hiérarchie immuable bien conçue, quel bénéfice obtient-on principalement ?',
  'options': ['Les objets deviennent plus faciles à partager entre threads',
              'Les objets ne peuvent plus être sérialisés',
              'Le polymorphisme disparaît',
              "La JVM n'utilise plus de heap"],
  'answer': 'A',
  'explanation': "L'immuabilité réduit les effets de bord et facilite l'usage concurrent."},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': 'Quel problème peut survenir avec un `parallelStream()` mal utilisé ?',
  'options': ['La disparition des exceptions compilées',
              'Une baisse de performances due au surcoût parallèle ou à des effets de bord non sûrs',
              "L'impossibilité d'utiliser des lambdas",
              'La suppression des doublons'],
  'answer': 'B',
  'explanation': "Le parallélisme n'est pas toujours bénéfique et peut poser des problèmes avec des traitements "
                 'stateful.'},
 {'category': 'Java',
  'difficulty': 'Avancé',
  'statement': "Pourquoi un `PreparedStatement` est-il plus sûr qu'une concaténation de chaînes pour une requête SQL ?",
  'options': ['Il chiffre automatiquement les données',
              'Il sépare la structure SQL des paramètres utilisateurs',
              'Il supprime les transactions',
              'Il transforme toutes les colonnes en index'],
  'answer': 'B',
  'explanation': "Les paramètres sont liés séparément, ce qui réduit fortement le risque d'injection SQL."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': 'Que signifie IoC dans Spring ?',
  'options': ['Input of Code', 'Inversion of Control', 'Instance of Component', 'Injection of Cache'],
  'answer': 'B',
  'explanation': "L'Inversion of Control délègue la création et la gestion des objets au conteneur Spring."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': 'Quelle annotation déclare couramment un composant de service métier ?',
  'options': ['@Service', '@Table', '@BeanFactory', '@InjectableController'],
  'answer': 'A',
  'explanation': '`@Service` marque une classe de service gérée par Spring.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': 'Quelle annotation est utilisée sur une classe exposant des endpoints REST ?',
  'options': ['@Repository', '@RestController', '@Entity', '@ConfigurationPropertiesScanOnly'],
  'answer': 'B',
  'explanation': '`@RestController` combine `@Controller` et `@ResponseBody` pour des API REST.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': "Que permet principalement l'injection de dépendances ?",
  'options': ['Augmenter la taille du JAR',
              'Réduire le couplage entre composants',
              'Remplacer la JVM',
              'Créer des jointures SQL'],
  'answer': 'B',
  'explanation': "L'injection de dépendances facilite le remplacement et le test des collaborations."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': "Quel composant est généralement chargé de l'accès aux données ?",
  'options': ['@Repository', '@ControllerAdvice', '@RestController', '@Scheduled'],
  'answer': 'A',
  'explanation': '`@Repository` identifie les composants de persistance.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Basique',
  'statement': 'Quel outil Spring Boot expose des endpoints de supervision comme `/actuator/health` ?',
  'options': ['Spring Batch', 'Actuator', 'Feign', 'Thymeleaf'],
  'answer': 'B',
  'explanation': 'Spring Boot Actuator fournit des informations de santé, métriques et supervision.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': 'Quelle différence majeure existe entre `@Component` et `@Bean` ?',
  'options': ['Aucune dans tous les cas',
              '`@Component` scanne une classe, `@Bean` déclare un objet via une méthode de configuration',
              '`@Bean` ne fonctionne pas avec Spring Boot',
              '`@Component` crée uniquement des repositories'],
  'answer': 'B',
  'explanation': "`@Component` repose sur le classpath scanning alors que `@Bean` enregistre le retour d'une méthode "
                 'de configuration.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel avantage offre `@Autowired` sur constructeur dans une classe de service ?',
  'options': ['Il masque les dépendances',
              'Il favorise des dépendances explicites et des tests plus simples',
              'Il évite toutes les annotations',
              'Il remplace JPA'],
  'answer': 'B',
  'explanation': "L'injection par constructeur rend les dépendances visibles et favorise l'immuabilité."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': 'À quoi sert typiquement une interface qui étend `JpaRepository<User, Long>` ?',
  'options': ['À compiler le JDK',
              "À fournir des opérations CRUD et de pagination sur l'entité User",
              'À créer un contrôleur MVC',
              'À sécuriser les mots de passe'],
  'answer': 'B',
  'explanation': 'Spring Data JPA génère des implémentations pour les accès CRUD courants.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': 'Que fait `@RequestBody` dans Spring MVC ?',
  'options': ['Il lit le corps HTTP et le convertit en objet Java',
              'Il chiffre automatiquement la requête',
              'Il ajoute une transaction SQL',
              'Il force une vue JSP'],
  'answer': 'A',
  'explanation': '`@RequestBody` désérialise le contenu de la requête vers un type Java.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': "Quel mécanisme Spring Security est souvent utilisé pour stocker les rôles d'un utilisateur authentifié "
               '?',
  'options': ['SecurityContext', 'JDBC URL', 'BeanFactory', 'DispatcherServlet'],
  'answer': 'A',
  'explanation': "Le `SecurityContext` contient l'authentification courante et ses autorités."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel est le rôle du `DispatcherServlet` dans Spring MVC ?',
  'options': ['Exécuter le garbage collector',
              'Recevoir les requêtes web et déléguer aux bons contrôleurs',
              'Créer des tables SQL',
              'Scanner les dépendances Maven'],
  'answer': 'B',
  'explanation': '`DispatcherServlet` est le front controller de Spring MVC.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': "Pourquoi limiter l'injection par champ (`field injection`) dans une application Spring moderne ?",
  'options': ["Parce qu'elle interdit JPA",
              "Parce qu'elle complique les tests et masque les dépendances",
              "Parce qu'elle désactive Actuator",
              "Parce qu'elle change le port HTTP"],
  'answer': 'B',
  'explanation': "L'injection par constructeur est plus explicite et plus simple à tester."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': 'Quel bénéfice principal apporte `@Transactional` sur une méthode de service métier ?',
  'options': ['Créer automatiquement des index',
              'Garantir une unité de travail cohérente avec commit/rollback',
              'Remplacer les contrôleurs REST',
              'Éviter toute exception Java'],
  'answer': 'B',
  'explanation': "Une transaction regroupe les opérations et permet un rollback en cas d'échec."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': 'Pourquoi exposer tous les endpoints Actuator en production peut-il être risqué ?',
  'options': ['Parce que Spring ne démarre plus',
              "Parce que certaines informations d'exploitation peuvent être sensibles",
              'Parce que JSON devient invalide',
              'Parce que JPA ne fonctionne plus'],
  'answer': 'B',
  'explanation': 'Les endpoints peuvent révéler des métriques, mappings ou détails internes utiles à un attaquant.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': "Dans Spring Data JPA, quel problème peut apparaître lorsqu'on sérialise directement une entité avec "
               'relations LAZY hors transaction ?',
  'options': ['Un code 201 automatique',
              'Une LazyInitializationException',
              'Une compilation plus lente',
              'Une perte du bean principal'],
  'answer': 'B',
  'explanation': 'Une relation LAZY non initialisée ne peut pas être chargée une fois la session fermée.'},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': "Quel choix améliore le plus la robustesse d'une API REST Spring ?",
  'options': ['Retourner systématiquement 200 OK',
              "Centraliser la gestion d'erreurs avec `@ControllerAdvice` et des statuts cohérents",
              'Utiliser uniquement des contrôleurs statiques',
              'Désactiver la validation'],
  'answer': 'B',
  'explanation': "Une gestion centralisée des erreurs rend l'API plus cohérente et prédictible."},
 {'category': 'Spring / Spring Boot',
  'difficulty': 'Avancé',
  'statement': "Pourquoi externaliser la configuration via `application.yml` et variables d'environnement ?",
  'options': ['Pour lier fortement le code à une machine',
              "Pour séparer configuration et code selon l'environnement",
              'Pour empêcher les tests',
              "Pour supprimer le besoin d'annotations"],
  'answer': 'B',
  'explanation': 'Cela facilite le déploiement sur plusieurs environnements sans modifier le code source.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': 'Quel ordre SQL sert à créer une table ?',
  'options': ['SELECT', 'INSERT', 'CREATE TABLE', 'UPDATE'],
  'answer': 'C',
  'explanation': '`CREATE TABLE` fait partie du DDL et crée une nouvelle table.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': 'Quelle clause permet de filtrer des lignes avant agrégation ?',
  'options': ['HAVING', 'ORDER BY', 'WHERE', 'GROUP BY'],
  'answer': 'C',
  'explanation': '`WHERE` filtre les lignes sources avant les regroupements.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': 'Quelle jointure retourne uniquement les lignes correspondantes dans les deux tables ?',
  'options': ['LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'FULL JOIN'],
  'answer': 'C',
  'explanation': '`INNER JOIN` conserve seulement les correspondances présentes dans les deux côtés.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': 'Quelle commande SQL ajoute une nouvelle ligne dans une table ?',
  'options': ['INSERT', 'ALTER', 'DROP', 'TRUNCATE'],
  'answer': 'A',
  'explanation': '`INSERT` ajoute des enregistrements.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': "Quelle fonction d'agrégation compte le nombre de lignes ?",
  'options': ['SUM', 'COUNT', 'AVG', 'MIN'],
  'answer': 'B',
  'explanation': "`COUNT` retourne le nombre de lignes ou de valeurs non nulles selon l'expression."},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Basique',
  'statement': "Que signifie le 'C' de l'acronyme ACID ?",
  'options': ['Cache', 'Consistency', 'Column', 'Cursor'],
  'answer': 'B',
  'explanation': 'ACID signifie Atomicity, Consistency, Isolation, Durability.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quelle clause filtre les groupes après un `GROUP BY` ?',
  'options': ['WHERE', 'HAVING', 'LIMIT', 'VALUES'],
  'answer': 'B',
  'explanation': "`HAVING` s'applique aux groupes déjà agrégés."},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': "Quel est l'effet principal d'un index sur une colonne fréquemment recherchée ?",
  'options': ['Il supprime les doublons automatiquement',
              'Il peut accélérer les lectures ciblées mais a un coût en écriture',
              'Il remplace les clés étrangères',
              'Il garantit la 3NF'],
  'answer': 'B',
  'explanation': 'Un index améliore souvent les recherches, au prix de stockage et de maintenance supplémentaires.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Dans une relation 1-N, où place-t-on généralement la clé étrangère ?',
  'options': ['Dans la table du côté N', 'Dans la table du côté 1', 'Dans une vue', 'Dans toutes les tables'],
  'answer': 'A',
  'explanation': 'La clé étrangère se trouve en général dans la table qui porte plusieurs occurrences liées au '
                 'parent.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quelle forme normale élimine principalement les dépendances partielles sur une clé composée ?',
  'options': ['1NF', '2NF', '3NF', 'BCNF'],
  'answer': 'B',
  'explanation': 'La 2NF traite les dépendances partielles par rapport aux clés candidates composées.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Que retourne une sous-requête utilisée avec `IN` ?',
  'options': ['Obligatoirement une seule ligne',
              'Un ensemble de valeurs comparables',
              'Une transaction active',
              'Un index bitmap'],
  'answer': 'B',
  'explanation': '`IN` compare une valeur à un ensemble retourné par la sous-requête.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel langage est spécifiquement associé à Oracle pour les blocs procéduraux ?',
  'options': ['T-SQL', 'PL/SQL', 'JPQL', 'XPath'],
  'answer': 'B',
  'explanation': 'PL/SQL étend SQL avec des structures procédurales côté Oracle.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': 'Pourquoi une transaction doit-elle être courte en environnement concurrent ?',
  'options': ['Pour changer le type des colonnes',
              'Pour réduire le temps de verrouillage et la contention',
              'Pour supprimer la normalisation',
              'Pour éviter les clés primaires'],
  'answer': 'B',
  'explanation': 'Des transactions courtes libèrent plus vite les ressources et limitent les blocages.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': 'Quel problème une mauvaise isolation peut-elle provoquer ?',
  'options': ['Dirty read', 'Compilation du schéma', 'Suppression des index', 'Encodage UTF-8'],
  'answer': 'A',
  'explanation': 'Une isolation trop faible peut permettre de lire des données non validées : dirty reads.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': 'Quand une table est en 3NF, quel objectif a été atteint ?',
  'options': ['Toutes les colonnes sont indexées',
              'Les dépendances transitives non clés ont été supprimées',
              "Il n'existe plus de valeurs nulles",
              'Toutes les requêtes sont optimisées'],
  'answer': 'B',
  'explanation': 'La 3NF vise à éliminer les dépendances transitives qui nuisent à la cohérence.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': 'Quel intérêt majeur apporte BCNF par rapport à 3NF ?',
  'options': ['Elle supprime les transactions',
              'Elle renforce la contrainte sur les déterminants pour réduire certaines anomalies restantes',
              'Elle remplace MERISE',
              'Elle interdit les jointures'],
  'answer': 'B',
  'explanation': 'BCNF est plus stricte que la 3NF lorsque des dépendances fonctionnelles particulières subsistent.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': 'Dans MERISE, quel modèle décrit surtout les données de manière conceptuelle, indépendante de '
               "l'implémentation ?",
  'options': ['MCD', 'MPD', 'MCT', 'JPA'],
  'answer': 'A',
  'explanation': 'Le MCD (modèle conceptuel de données) décrit entités, associations et cardinalités.'},
 {'category': 'SQL / Bases de données',
  'difficulty': 'Avancé',
  'statement': "Quelle requête est généralement la plus sûre contre l'injection lorsqu'elle provient d'une application "
               '?',
  'options': ['Une concaténation de chaînes SQL',
              'Une requête préparée paramétrée',
              'Une requête copiée depuis un log',
              'Une vue matérialisée'],
  'answer': 'B',
  'explanation': "Les paramètres liés dans une requête préparée évitent d'interpréter l'entrée comme du code SQL."},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': "Quel langage structure le contenu d'une page web ?",
  'options': ['CSS', 'HTML', 'SQL', 'JSON'],
  'answer': 'B',
  'explanation': 'HTML décrit la structure sémantique des pages web.'},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': "Quel langage est principalement utilisé pour la mise en forme d'une page web ?",
  'options': ['CSS', 'Java', 'HTTP', 'REST'],
  'answer': 'A',
  'explanation': 'CSS contrôle la présentation visuelle : couleurs, marges, disposition, etc.'},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': 'Quel format léger est couramment utilisé pour échanger des données dans une API REST ?',
  'options': ['PDF', 'JSON', 'BMP', 'CSV binaire'],
  'answer': 'B',
  'explanation': 'JSON est très utilisé pour les échanges de données entre client et serveur.'},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': "Quel code HTTP signifie généralement 'Not Found' ?",
  'options': ['200', '201', '404', '500'],
  'answer': 'C',
  'explanation': "404 indique qu'aucune ressource ne correspond à l'URL demandée."},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': 'Quelle méthode HTTP est généralement utilisée pour récupérer une ressource sans la modifier ?',
  'options': ['POST', 'PATCH', 'GET', 'DELETE'],
  'answer': 'C',
  'explanation': 'GET sert à lire une ressource et doit être sûre du point de vue sémantique.'},
 {'category': 'Développement Web',
  'difficulty': 'Basique',
  'statement': "Quel risque de sécurité correspond à l'injection de script dans une page vue par d'autres utilisateurs "
               '?',
  'options': ['CSRF', 'XSS', 'Deadlock', 'Race condition'],
  'answer': 'B',
  'explanation': "Le XSS permet d'exécuter du JavaScript malveillant dans le navigateur de la victime."},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel en-tête HTTP indique souvent le type de contenu renvoyé ?',
  'options': ['Authorization', 'Content-Type', 'Cache-Control', 'Origin'],
  'answer': 'B',
  'explanation': '`Content-Type` décrit le média renvoyé, par exemple `application/json`.'},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': 'Quelle différence décrit le mieux REST ?',
  'options': ['REST impose XML uniquement',
              'REST repose sur des ressources identifiées et des verbes HTTP standard',
              'REST remplace TCP',
              'REST fonctionne sans HTTP'],
  'answer': 'B',
  'explanation': "REST organise les échanges autour de ressources et d'opérations standardisées."},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel mécanisme aide à limiter les attaques CSRF sur un formulaire authentifié ?',
  'options': ['Un token CSRF côté serveur',
              'Une variable globale JavaScript',
              'Un commentaire HTML',
              'Une jointure SQL'],
  'answer': 'A',
  'explanation': 'Un token imprévisible validé par le serveur réduit les requêtes forgées inter-sites.'},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': 'Pourquoi valider aussi côté serveur des données déjà validées côté client ?',
  'options': ['Parce que le navigateur garantit déjà tout',
              'Parce que la validation côté client peut être contournée',
              "Pour supprimer le besoin d'API",
              "Pour éviter l'UTF-8"],
  'answer': 'B',
  'explanation': "Le client n'est pas digne de confiance : les contrôles serveur restent indispensables."},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': "Quel sélecteur CSS cible un élément avec l'identifiant `menu` ?",
  'options': ['.menu', '#menu', 'menu[]', '@menu'],
  'answer': 'B',
  'explanation': 'Le caractère `#` cible un identifiant en CSS.'},
 {'category': 'Développement Web',
  'difficulty': 'Intermédiaire',
  'statement': "Quel statut HTTP convient généralement le mieux après la création réussie d'une ressource par POST ?",
  'options': ['200 OK', '201 Created', '204 No Content', '304 Not Modified'],
  'answer': 'B',
  'explanation': "201 indique qu'une nouvelle ressource a été créée avec succès."},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': 'Quelle mesure réduit le plus le risque XSS persistant dans une application web ?',
  'options': ['Augmenter la RAM du serveur',
              'Échapper/encoder les données non fiables selon le contexte de rendu',
              'Masquer les erreurs SQL',
              'Utiliser uniquement GET'],
  'answer': 'B',
  'explanation': "L'encodage contextuel des sorties et la sanitation ciblée sont des défenses clés contre le XSS."},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': "Pourquoi une API REST ne devrait-elle pas exposer directement les messages d'erreur internes d'une "
               'base de données ?',
  'options': ["Parce qu'ils peuvent révéler des détails sensibles facilitant l'attaque",
              "Parce qu'ils ralentissent CSS",
              "Parce qu'ils empêchent JSON",
              "Parce qu'ils désactivent HTTP/2"],
  'answer': 'A',
  'explanation': 'Les messages internes peuvent divulguer schéma, requêtes ou stack traces utiles à un attaquant.'},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': "Quel attribut de cookie aide à limiter l'accès du JavaScript au cookie de session ?",
  'options': ['Secure', 'HttpOnly', 'Path=/api', 'Expires'],
  'answer': 'B',
  'explanation': "`HttpOnly` empêche l'accès au cookie via `document.cookie`, limitant certains impacts XSS."},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': 'Quel scénario décrit le mieux une injection SQL ?',
  'options': ['Un script CSS modifie la couleur du site',
              "Une entrée utilisateur modifie la structure d'une requête SQL concaténée",
              'Un navigateur met en cache une image',
              'Un token JWT expire'],
  'answer': 'B',
  'explanation': "L'injection SQL survient lorsque l'entrée utilisateur est interprétée comme du code SQL."},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': "Quelle architecture front/back améliore souvent la maintenabilité d'une application web complexe ?",
  'options': ['Mélanger requêtes SQL, HTML et logique métier dans le même fichier',
              'Séparer clairement présentation, logique client et API serveur',
              'Supprimer tout cache HTTP',
              'Utiliser uniquement des variables globales'],
  'answer': 'B',
  'explanation': "La séparation des couches réduit le couplage et simplifie l'évolution."},
 {'category': 'Développement Web',
  'difficulty': 'Avancé',
  'statement': 'Pour une API publique, quel mécanisme renforce le plus la robustesse face aux abus ?',
  'options': ['Désactiver les logs',
              'Mettre en place authentification, autorisation et rate limiting',
              'Répondre 200 à toutes les requêtes',
              'Supprimer TLS'],
  'answer': 'B',
  'explanation': "L'authentification et la limitation de débit réduisent les usages abusifs et malveillants."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': 'Que mesure principalement la notation Big O ?',
  'options': ['La couleur du code',
              "L'ordre de croissance du coût d'un algorithme",
              "Le nombre exact d'octets utilisés par la JVM",
              'La version du compilateur'],
  'answer': 'B',
  'explanation': "Big O exprime l'évolution asymptotique du temps ou de l'espace selon la taille d'entrée."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': 'Quel algorithme de recherche nécessite généralement un tableau trié ?',
  'options': ['Recherche linéaire', 'Recherche binaire', 'Parcours en profondeur', 'Tri par insertion'],
  'answer': 'B',
  'explanation': "La recherche binaire exploite l'ordre des éléments pour diviser l'intervalle en deux."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': 'Quelle structure suit le principe FIFO ?',
  'options': ['Pile', 'File', 'Arbre binaire', 'Tas'],
  'answer': 'B',
  'explanation': "Une file traite en premier l'élément arrivé en premier."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': 'Quelle structure suit le principe LIFO ?',
  'options': ['Pile', 'File', 'Graphe', 'Table de hachage'],
  'answer': 'A',
  'explanation': 'Une pile retourne en premier le dernier élément ajouté.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': 'Dans une liste chaînée simple, chaque nœud contient généralement :',
  'options': ['Seulement une clé primaire',
              'Une valeur et un pointeur vers le suivant',
              'Un tableau trié complet',
              'Deux hash maps'],
  'answer': 'B',
  'explanation': 'Un nœud stocke une donnée et une référence vers le nœud suivant.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Basique',
  'statement': "Quel parcours visite d'abord la racine, puis le sous-arbre gauche, puis le sous-arbre droit ?",
  'options': ['Infixe', 'Postfixe', 'Préfixe', 'Largeur'],
  'answer': 'C',
  'explanation': "Le parcours préfixe suit l'ordre racine-gauche-droite."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': "Quelle est la complexité temporelle moyenne d'une recherche binaire ?",
  'options': ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
  'answer': 'B',
  'explanation': "À chaque étape, la recherche binaire réduit de moitié l'espace de recherche."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel tri a une complexité moyenne de O(n log n) et repose sur la stratégie diviser pour régner ?',
  'options': ['Bubble sort', 'Merge sort', 'Selection sort', 'Insertion sort'],
  'answer': 'B',
  'explanation': 'Merge sort divise le tableau puis fusionne les sous-tableaux triés.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Dans un arbre binaire de recherche, quelle propriété est vraie ?',
  'options': ['Tous les nœuds ont deux enfants',
              'Les valeurs du sous-arbre gauche sont inférieures à la racine',
              'Les feuilles sont chaînées entre elles',
              'La racine est toujours la médiane exacte'],
  'answer': 'B',
  'explanation': 'Un BST impose un ordre relatif gauche < racine < droite.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quel algorithme parcourt typiquement un graphe niveau par niveau ?',
  'options': ['DFS', 'BFS', 'Dijkstra sans file', 'Merge sort'],
  'answer': 'B',
  'explanation': 'Le Breadth-First Search visite les voisins par couches successives.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': 'Quand une fonction récursive doit-elle impérativement définir un cas de base ?',
  'options': ['Seulement en Java',
              "Toujours, pour garantir l'arrêt",
              'Jamais si elle utilise une liste',
              'Uniquement pour les graphes'],
  'answer': 'B',
  'explanation': "Sans cas de base, la récursion risque de ne jamais s'arrêter."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Intermédiaire',
  'statement': "Quel coût a généralement l'accès au ième élément d'une liste chaînée simple ?",
  'options': ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
  'answer': 'C',
  'explanation': "Il faut parcourir séquentiellement les nœuds jusqu'à la position demandée."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': 'Quel risque principal présente une implémentation récursive profonde sans optimisation de pile ?',
  'options': ["Une collision d'index SQL",
              'Un dépassement de pile (`stack overflow`)',
              'Une perte du garbage collector',
              'Un deadlock réseau'],
  'answer': 'B',
  'explanation': 'Chaque appel consomme de la pile ; une profondeur excessive peut provoquer un débordement.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': "Dans quel cas un `HashMap` se rapproche-t-il le plus d'une recherche en O(n) ?",
  'options': ['Quand la fonction de hachage répartit bien les clés',
              'Quand de nombreuses collisions dégradent les buckets',
              'Quand les clés sont immuables',
              'Quand la table est vide'],
  'answer': 'B',
  'explanation': "Des collisions excessives peuvent dégrader les performances d'accès."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': 'Quel avantage offre un arbre équilibré par rapport à un arbre binaire de recherche dégénéré ?',
  'options': ['Il garantit des opérations proches de O(log n)',
              'Il supprime la mémoire utilisée',
              'Il interdit les doublons dans tous les cas',
              'Il remplace BFS'],
  'answer': 'A',
  'explanation': "L'équilibrage limite la hauteur et préserve de bonnes performances."},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': 'Pourquoi Dijkstra ne convient-il pas tel quel avec des poids négatifs ?',
  'options': ["Parce qu'il nécessite un graphe complet",
              "Parce que son hypothèse de relaxation progressive n'est plus valide",
              "Parce qu'il utilise trop peu de mémoire",
              "Parce qu'il trie en O(n²)"],
  'answer': 'B',
  'explanation': 'Des arêtes négatives peuvent invalider le choix glouton de Dijkstra.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': 'Quel critère guide principalement le choix entre tableau dynamique et liste chaînée ?',
  'options': ["La couleur de l'IDE",
              "Les profils d'accès, d'insertion et les contraintes mémoire",
              'Le nom des variables',
              "Le système d'exploitation uniquement"],
  'answer': 'B',
  'explanation': 'Le bon choix dépend des opérations dominantes et des compromis mémoire/performance.'},
 {'category': 'Algorithmes et structures de données',
  'difficulty': 'Avancé',
  'statement': 'Quelle structure est la plus adaptée pour implémenter efficacement une file de priorité classique ?',
  'options': ['Un tas binaire', 'Une liste simplement chaînée non triée', 'Un tableau 2D', 'Une pile'],
  'answer': 'A',
  'explanation': 'Le tas binaire offre de bonnes complexités pour insertion et extraction du minimum/maximum.'}]

TOPIC_BANKS = {'Génie logiciel': [('Cycle en V',
                     'relie explicitement chaque phase de spécification à une phase de vérification ou de validation '
                     'correspondante',
                     'sécuriser un projet où la traçabilité entre exigences et tests est critique',
                     "le suivre de façon rigide rend l'intégration tardive des retours métier beaucoup plus coûteuse"),
                    ('Modèle en spirale',
                     "organise le projet en itérations guidées par l'analyse et la réduction progressive des risques",
                     'prototyper un produit innovant dont les risques techniques sont encore élevés',
                     "ignorer l'étape d'évaluation des risques annule l'intérêt principal du modèle"),
                    ('Kanban',
                     'visualise le flux de travail et limite explicitement le travail en cours',
                     'réduire le multitâche en pilotant le flux avec des limites WIP',
                     'augmenter le WIP pour occuper tout le monde dégrade souvent le débit global'),
                    ('Extreme Programming (XP)',
                     "met l'accent sur le feedback rapide, le refactoring, le pair programming et l'intégration "
                     'continue',
                     "améliorer la qualité d'un produit qui évolue vite grâce à des boucles courtes",
                     "conserver des branches longues contredit la logique d'intégration continue de XP"),
                    ('SAFe',
                     "cadre d'agilité à l'échelle utilisé pour coordonner plusieurs équipes autour de trains de "
                     'livraison',
                     'aligner plusieurs équipes sur une planification commune sans perdre les incréments réguliers',
                     'le transformer en simple couche de reporting fait perdre sa valeur de synchronisation'),
                    ("Diagramme de cas d'utilisation",
                     "représente les acteurs et les objectifs métier vus depuis l'extérieur du système",
                     'clarifier les interactions utilisateur-système avant le design détaillé',
                     'y décrire des attributs techniques de classes mélange besoin métier et conception'),
                    ("Diagramme d'activité",
                     'décrit un flux de travail avec actions, décisions, parallélisme et synchronisations',
                     'modéliser un processus métier ou un algorithme procédural',
                     "l'utiliser pour représenter l'héritage entre classes est une mauvaise abstraction"),
                    ("Diagramme d'état",
                     "montre les états d'un objet et les transitions provoquées par des événements",
                     "spécifier le comportement d'une commande ou d'une session selon son état courant",
                     'oublier les événements de sortie conduit souvent à un automate incomplet'),
                    ('Decorator',
                     'ajoute dynamiquement des responsabilités à un objet sans modifier sa classe concrète',
                     'empiler des comportements comme journalisation, cache ou compression',
                     "l'utiliser pour gérer des variantes purement figées peut nuire à la lisibilité"),
                    ('Adapter',
                     "convertit l'interface d'un composant existant vers celle attendue par le client",
                     'intégrer une bibliothèque tierce incompatible sans changer son code source',
                     "détourner Adapter pour ajouter des responsabilités le rapproche d'un Decorator mal choisi"),
                    ('Facade',
                     'fournit une interface simple à un sous-système composé de plusieurs composants',
                     'masquer une orchestration technique derrière une API plus simple à consommer',
                     'si la façade concentre toute la logique métier elle devient un point de couplage excessif'),
                    ('Git rebase',
                     'réapplique des commits sur une autre base afin de produire un historique plus linéaire',
                     "mettre à jour une branche locale avant de l'intégrer en limitant les commits de fusion",
                     "réécrire l'historique partagé sans coordination peut perturber les autres développeurs"),
                    ('GitFlow',
                     'propose un workflow avec branches dédiées comme feature, develop, release et hotfix',
                     'organiser un cycle de livraison formel avec stabilisation avant mise en production',
                     'le conserver tel quel sur un flux de déploiement continu peut ajouter une complexité inutile'),
                    ('CI/CD',
                     "automatise l'intégration, les vérifications et éventuellement la livraison ou le déploiement",
                     'détecter rapidement les régressions après chaque changement intégré',
                     "déployer sans garde-fous ni validation progressive augmente le risque d'incident"),
                    ('Docker',
                     'encapsule une application et ses dépendances dans une image exécutable reproductible',
                     "obtenir un environnement de build et d'exécution cohérent entre machines",
                     'confondre image immuable et stockage persistant mène à de mauvaises stratégies de données'),
                    ('Kubernetes',
                     'orchestre des conteneurs via des objets comme pods, deployments et services',
                     "gérer le scaling et la haute disponibilité d'une application conteneurisée en cluster",
                     'déployer sans requests ni limits de ressources peut dégrader la stabilité du cluster')],
 'Java': [('Modificateurs d’accès',
           "contrôlent la visibilité d'une classe, d'un attribut ou d'une méthode avec public, protected, "
           'package-private et private',
           "encapsuler l'état interne d'une classe tout en exposant seulement l'API utile",
           'rendre inutilement publics des détails internes augmente le couplage et la surface de changement'),
          ('Interfaces et classes abstraites',
           'permettent de définir des contrats communs, les interfaces privilégiant le comportement attendu et les '
           'classes abstraites le code partagé',
           'factoriser un contrat commun tout en laissant plusieurs implémentations possibles',
           "forcer l'héritage d'une hiérarchie rigide alors qu'un simple contrat suffirait réduit la flexibilité"),
          ('this et super',
           "référencent respectivement l'instance courante et les membres de la classe parente",
           "lever l'ambiguïté entre attribut et paramètre ou réutiliser le constructeur parent",
           "mal employer super dans une hiérarchie peut casser l'initialisation attendue"),
          ('Constructeurs et surcharge',
           'initialisent les objets et permettent plusieurs signatures adaptées à différents contextes de création',
           'proposer plusieurs manières valides de construire un objet sans multiplier les noms de méthodes',
           'dupliquer une logique complexe dans plusieurs constructeurs favorise les incohérences'),
          ('HashMap et TreeMap',
           "diffèrent surtout par l'ordre des clés et les structures sous-jacentes utilisées",
           "choisir TreeMap lorsqu'il faut parcourir les clés triées naturellement ou par Comparator",
           'utiliser des clés mutables peut rendre les recherches incohérentes dans une map'),
          ('HashSet et TreeSet',
           "assurent l'unicité mais TreeSet maintient aussi un ordre trié des éléments",
           'éliminer des doublons tout en conservant un ordre trié déterministe',
           "insérer des éléments non comparables dans un TreeSet provoque un problème d'ordre"),
          ('Queue, Deque et PriorityQueue',
           "représentent des files où l'ordre de sortie dépend du modèle FIFO, double extrémité ou priorité",
           "modéliser une file d'attente, une pile double face ou une extraction par priorité",
           "supposer qu'une PriorityQueue itère dans l'ordre trié complet est une erreur fréquente"),
          ('Exceptions checked et unchecked',
           "se distinguent par l'obligation ou non de les déclarer ou capturer à la compilation",
           "signaler explicitement des échecs récupérables comme des problèmes d'entrée-sortie",
           'attraper Exception partout masque souvent des défauts de conception ou de traitement'),
          ('try-with-resources',
           'ferme automatiquement les ressources qui implémentent AutoCloseable',
           "garantir la libération correcte d'un flux ou d'une connexion même en cas d'erreur",
           "oublier qu'une exception de fermeture peut être suppressée complique parfois le diagnostic"),
          ('synchronized, wait et notify',
           "coordonnent l'accès concurrent à un état partagé via un moniteur",
           "faire coopérer plusieurs threads autour d'une file partagée en évitant les races",
           "appeler wait ou notify hors section synchronisée déclenche une erreur d'exécution"),
          ('CompletableFuture',
           'compose des traitements asynchrones sans bloquer systématiquement le thread appelant',
           'enchaîner des appels distants ou des calculs dépendants de façon non bloquante',
           "bloquer trop tôt avec join sur chaque étape annule l'intérêt de la composition asynchrone"),
          ('NIO',
           'propose des buffers, channels et opérations plus adaptées aux E/S performantes',
           'traiter efficacement de gros volumes de données ou des échanges réseau non bloquants',
           "copier sans comprendre l'état position-limit d'un Buffer produit souvent des lectures erronées"),
          ('Reflection',
           "inspecte ou invoque dynamiquement des types, méthodes, champs et annotations à l'exécution",
           'construire un framework, un mapper ou un outil qui découvre des métadonnées au runtime',
           'en abuser réduit la lisibilité, la sécurité de type et parfois les performances'),
          ('Annotations Java',
           'attachent des métadonnées lisibles par le compilateur, les outils ou la JVM',
           'marquer des éléments pour la configuration déclarative ou la génération de code',
           "croire qu'une annotation produit un effet sans traitement associé est une confusion classique"),
          ('Sérialisation',
           "convertit l'état d'un objet en flux de bytes pour stockage ou transport",
           'persister ou transmettre un objet lorsque ce mécanisme est explicitement prévu',
           'sérialiser des types non maîtrisés ou des secrets sans précaution crée des risques de sécurité'),
          ('JVM, heap, stack et classloader',
           "répartissent l'exécution entre pile d'appels, mémoire des objets, chargement des classes et compilation "
           'JIT',
           'diagnostiquer une fuite mémoire, une StackOverflowError ou un problème de chargement de classes',
           "confondre pile d'appels et heap mène à de mauvais diagnostics de performance ou de mémoire")],
 'Spring / Spring Boot': [('Injection par constructeur',
                           "rend les dépendances obligatoires explicites au moment de l'instanciation",
                           'obtenir des services plus faciles à tester et plus simples à rendre immuables',
                           "mélanger trop d'injections révèle souvent une classe qui porte trop de responsabilités"),
                          ('Scopes de beans',
                           "déterminent la durée de vie et la portée d'un bean comme singleton, prototype, request ou "
                           'session',
                           "adapter le cycle de vie d'un composant à son usage applicatif",
                           'injecter un bean request dans un singleton sans mécanisme adapté crée des surprises de '
                           'portée'),
                          ('ApplicationContext et BeanFactory',
                           'sont des conteneurs Spring, le premier offrant davantage de services applicatifs que le '
                           'second',
                           "bénéficier d'événements, d'internationalisation et d'une intégration plus riche dans une "
                           'application Spring moderne',
                           'se limiter à BeanFactory fait perdre des fonctionnalités fréquemment attendues par '
                           "l'écosystème Spring"),
                          ('@Qualifier et @Primary',
                           "aident à lever l'ambiguïté lorsqu'il existe plusieurs beans compatibles avec le même type",
                           "sélectionner explicitement l'implémentation correcte d'une dépendance",
                           "compter sur l'ordre de scan plutôt que sur un choix explicite rend l'injection fragile"),
                          ('@Value et @ConfigurationProperties',
                           "permettent d'injecter de la configuration externe dans les composants",
                           'lier proprement des propriétés applicatives vers une structure de configuration dédiée',
                           'disperser des dizaines de @Value rend la configuration plus difficile à maintenir'),
                          ('@Profile et @Conditional',
                           "activent des beans selon l'environnement ou des conditions techniques",
                           "changer d'implémentation entre développement, test et production sans dupliquer le code "
                           'métier',
                           'multiplier des conditions opaques peut rendre le contexte Spring difficile à comprendre'),
                          ('@PathVariable et @RequestParam',
                           "extraient respectivement des valeurs du chemin d'URL et de la chaîne de requête",
                           'modéliser proprement des identifiants de ressource et des filtres optionnels',
                           "confondre identité de ressource et filtre de recherche rend souvent l'API moins claire"),
                          ('ResponseEntity',
                           'permet de contrôler explicitement statut HTTP, en-têtes et corps de réponse',
                           "retourner un code 201, 204 ou un en-tête Location cohérent avec l'opération",
                           "retourner toujours 200 OK même en cas d'erreur métier brouille le contrat HTTP"),
                          ('@ExceptionHandler et @ControllerAdvice',
                           'centralisent la transformation des exceptions en réponses HTTP cohérentes',
                           'uniformiser les erreurs renvoyées par plusieurs contrôleurs',
                           'laisser remonter des exceptions techniques brutes expose des détails internes inutiles'),
                          ('Auto-configuration',
                           'configure automatiquement des composants Spring Boot à partir du classpath et des '
                           'propriétés',
                           'démarrer rapidement un service avec peu de configuration explicite',
                           "supposer qu'une auto-configuration correspond toujours exactement au besoin peut masquer "
                           'des choix implicites'),
                          ('Starters Spring Boot',
                           'regroupent des dépendances cohérentes pour une fonctionnalité donnée',
                           'ajouter rapidement le support web, data ou security avec un ensemble compatible',
                           "empiler des starters sans comprendre ce qu'ils apportent grossit inutilement "
                           "l'application"),
                          ('Relations JPA',
                           'modélisent les associations entre entités via @OneToMany, @ManyToOne ou @ManyToMany',
                           'exprimer un domaine persistant en gardant la bonne cardinalité entre objets',
                           "ignorer le côté propriétaire d'une relation entraîne souvent des mises à jour inattendues"),
                          ('JPQL, requêtes natives et Specifications',
                           "offrent plusieurs niveaux d'expressivité pour interroger les données",
                           'construire des recherches dynamiques sans concaténer du SQL applicatif fragile',
                           'utiliser du natif partout réduit la portabilité et contourne certains bénéfices de JPA'),
                          ('Paging et Sorting',
                           'limitent le volume de données renvoyé et ordonnent les résultats de façon contrôlée',
                           "exposer une API listant proprement des milliers d'enregistrements",
                           'retourner des collections massives sans pagination dégrade mémoire, réseau et UX'),
                          ('Spring Security, JWT, CSRF et CORS',
                           "couvre l'authentification, l'autorisation et plusieurs mécanismes de sécurité web",
                           "protéger une API ou une application web selon son mode d'authentification et ses clients",
                           'désactiver CSRF ou CORS sans comprendre le contexte de menace crée des failles évitables'),
                          ('AOP Spring',
                           'applique des préoccupations transverses via des aspects et des pointcuts',
                           'centraliser journalisation, métriques ou sécurité autour de plusieurs méthodes',
                           'cacher trop de logique métier dans des aspects rend le comportement plus difficile à '
                           'suivre')],
 'SQL / Bases de données': [('Modèle relationnel et NoSQL',
                             'opposent surtout des garanties de schéma, de jointures et de cohérence à des modèles '
                             'plus souples ou distribués',
                             'choisir un SGBD cohérent avec les besoins de structure, de requêtes et de scalabilité',
                             'adopter NoSQL sans besoin réel de flexibilité ou de distribution complexifie inutilement '
                             'le système'),
                            ('MERISE',
                             'structure la conception des données et des traitements via des modèles comme MCD, MLD et '
                             'MPD',
                             "passer d'une vision métier des entités à une représentation logique puis physique",
                             'confondre MCD et MPD fait perdre la séparation entre métier et implémentation'),
                            ('Première forme normale',
                             "impose des attributs atomiques et l'absence de groupes répétitifs dans une table",
                             "éliminer les colonnes multivaluées avant d'aller vers des formes normales supérieures",
                             'stocker plusieurs valeurs dans une même cellule complique recherche, tri et intégrité'),
                            ('Quatrième forme normale',
                             'vise à éliminer certaines dépendances multivaluées indépendantes',
                             'décomposer une table quand plusieurs listes indépendantes coexistent pour la même clé',
                             'ignorer une dépendance multivaluée peut recréer des redondances même après BCNF'),
                            ('DDL, DML et DQL',
                             'regroupent respectivement la définition du schéma, la manipulation des données et '
                             "l'interrogation",
                             'distinguer clairement création de structure, modification de lignes et lecture',
                             'mélanger sans précaution des ordres de structure en production accroît le risque '
                             'opérationnel'),
                            ('ORDER BY, DISTINCT et LIMIT',
                             'servent à trier, dédupliquer ou borner un résultat',
                             'préparer un résultat paginé ou présenter proprement un classement',
                             "compter sur l'ordre naturel sans ORDER BY produit des résultats non garantis"),
                            ('LEFT, RIGHT, FULL, CROSS et SELF JOIN',
                             "déterminent quelles combinaisons de lignes sont conservées lors d'une jointure",
                             "choisir la jointure adaptée selon que l'on veut garder ou non les lignes sans "
                             'correspondance',
                             'placer un filtre au mauvais endroit peut transformer involontairement une LEFT JOIN en '
                             'INNER JOIN'),
                            ('Sous-requête corrélée',
                             'réévalue sa condition pour chaque ligne de la requête externe',
                             "exprimer une condition dépendant de la ligne courante lorsqu'une jointure n'est pas la "
                             'plus claire',
                             'les sous-requêtes corrélées mal maîtrisées peuvent coûter cher en performance'),
                            ('GROUP BY et HAVING',
                             'agrègent des lignes puis filtrent éventuellement les groupes obtenus',
                             "calculer des totaux par client, produit ou période avec des critères sur l'agrégat",
                             'sélectionner des colonnes non agrégées et non groupées crée des résultats ambigus ou '
                             'invalides'),
                            ('Fonctions de fenêtre',
                             'calculent des valeurs analytiques sur des ensembles de lignes liés sans les fusionner',
                             'produire un rang, un cumul ou un précédent/suivant par partition',
                             'oublier ORDER BY dans une fenêtre peut rendre le résultat analytique incohérent'),
                            ('CTE',
                             'nomme une sous-requête avec WITH pour clarifier ou structurer une requête complexe',
                             'découper un calcul SQL difficile à lire en étapes explicites',
                             "enchaîner des CTE inutiles peut parfois compliquer le plan d'exécution"),
                            ('Vues',
                             'encapsulent une requête nommée réutilisable exposée comme une table logique',
                             "simplifier l'accès à des jointures fréquentes ou restreindre certaines colonnes",
                             "oublier qu'une vue complexe cache du coût peut faire croire à tort qu'elle est gratuite"),
                            ('Index B-tree, hash, unique et composite',
                             "accélèrent certaines recherches au prix d'un coût d'écriture et de stockage "
                             'supplémentaire',
                             'optimiser des filtres ou tris réellement utilisés par les requêtes critiques',
                             'multiplier les index peu utiles ralentit les INSERT, UPDATE et DELETE'),
                            ('Contraintes',
                             'imposent des règles comme PK, FK, UNIQUE, CHECK, NOT NULL ou DEFAULT',
                             "faire respecter l'intégrité des données au plus près de leur stockage",
                             'déporter toute validation hors de la base fragilise la cohérence des données'),
                            ('Isolation, verrous et ACID',
                             'encadrent la cohérence transactionnelle et la concurrence entre opérations',
                             "choisir un niveau d'isolation adapté entre cohérence forte et débit concurrent",
                             'tenir des verrous longtemps accroît fortement la contention et les blocages'),
                            ('Procédures, triggers, fonctions, EXPLAIN et CAP',
                             "couvrent la logique côté base, l'analyse de plans et les compromis de systèmes "
                             'distribués',
                             'analyser une requête lente ou exécuter une logique encadrée près des données lorsque '
                             "c'est justifié",
                             'placer trop de logique cachée dans des triggers rend le comportement global plus '
                             'difficile à prévoir')],
 'Développement Web': [('HTML sémantique',
                        'utilise des balises comme header, nav, main, article ou footer pour donner du sens au contenu',
                        'améliorer accessibilité, référencement et structure de document',
                        'remplacer systématiquement des balises sémantiques par des div anonymes appauvrit le '
                        'document'),
                       ('Formulaires HTML5',
                        'ajoutent des types de champs, contraintes natives et attributs de validation',
                        'obtenir une validation de base et une meilleure ergonomie côté navigateur',
                        'croire que la validation navigateur remplace les contrôles serveur expose des failles'),
                       ('Web Storage',
                        'stocke des données clés-valeurs côté navigateur via localStorage ou sessionStorage',
                        'mémoriser des préférences client non sensibles sans aller en base à chaque fois',
                        'y placer des secrets durables ou des données critiques côté client est risqué'),
                       ('Flexbox',
                        "optimise l'alignement et la distribution d'éléments le long d'un axe principal",
                        "centrer ou répartir facilement des composants dans une barre d'outils ou une carte",
                        'vouloir modéliser toute une grille bidimensionnelle complexe uniquement avec Flexbox est '
                        'souvent laborieux'),
                       ('CSS Grid',
                        'gère des mises en page bidimensionnelles avec lignes, colonnes et zones',
                        'concevoir un layout complexe de page avec entête, sidebar et contenu',
                        'oublier le comportement des tailles implicites peut produire des débordements inattendus'),
                       ('Media queries et responsive design',
                        'adaptent la présentation selon largeur, média ou préférences utilisateur',
                        "faire évoluer l'interface du mobile au desktop avec le même HTML",
                        'concevoir uniquement pour un écran large puis réduire ensuite donne souvent un responsive '
                        'fragile'),
                       ('Hoisting JavaScript',
                        "correspond au comportement de préparation des déclarations avant l'exécution effective du "
                        'code',
                        'comprendre pourquoi var et les déclarations de fonctions ne se comportent pas comme let ou '
                        'const',
                        "supposer qu'une variable let est utilisable avant sa déclaration mène à la temporal dead "
                        'zone'),
                       ('Closures',
                        "permettent à une fonction de conserver l'accès à son environnement lexical",
                        'encapsuler un état privé ou fabriquer des fonctions spécialisées',
                        'capturer une variable mutable inattendue dans une boucle peut produire un résultat '
                        'surprenant'),
                       ('this, prototypes et classes ES6',
                        'décrivent le modèle objet de JavaScript et la résolution dynamique du contexte',
                        'partager des méthodes entre objets et comprendre le binding du contexte',
                        "perdre le bon this lors du passage d'une méthode comme callback provoque des bugs fréquents"),
                       ('Promises, async/await et event loop',
                        "structurent l'asynchronisme au-dessus de la boucle d'événements du navigateur ou de Node.js",
                        'enchaîner proprement des appels non bloquants comme fetch sans pyramide de callbacks',
                        "bloquer le thread principal avec des traitements lourds fige l'interface malgré async/await"),
                       ('DOM, événements et fetch',
                        'permettent de modifier la page, réagir aux interactions et appeler des ressources HTTP',
                        "mettre à jour dynamiquement l'interface après une action utilisateur ou une réponse API",
                        "oublier la délégation d'événements ou la gestion des erreurs réseau produit des comportements "
                        'fragiles'),
                       ('TypeScript',
                        'ajoute un système de types statiques optionnel au-dessus de JavaScript',
                        'sécuriser des contrats entre modules dans une base de code front volumineuse',
                        "contourner les types avec any partout annule l'intérêt principal de TypeScript"),
                       ('REST, verbes HTTP et idempotence',
                        'reposent sur des ressources, des représentations et des opérations dont certaines sont '
                        'idempotentes',
                        'concevoir une API où GET lit, PUT remplace et DELETE supprime de façon cohérente',
                        'utiliser POST pour tout brouille le contrat et complique cache, tests et interopérabilité'),
                       ('HTTP, cookies, sessions et CORS',
                        "couvrent le transport des requêtes, l'état côté navigateur et la politique d'origine croisée",
                        "gérer une authentification de session ou des appels d'un front vers une API distante",
                        'ouvrir CORS à toutes les origines avec des credentials sans réflexion est dangereux'),
                       ('JSON, XML, WebSockets et GraphQL',
                        "illustrent différents formats ou modes d'échange de données entre client et serveur",
                        'choisir un protocole ou format adapté à un besoin de push, de contrat ou de sélection fine',
                        'utiliser WebSocket pour un simple échange requête-réponse apporte souvent une complexité '
                        'inutile'),
                       ('XSS, CSRF, CSP, JWT, OAuth2, OIDC et hachage des mots de passe',
                        'rassemblent plusieurs mécanismes de sécurité web côté navigateur et côté identité',
                        'protéger une application exposée en combinant encodage de sortie, jetons, politiques et '
                        'hachage robuste',
                        'stocker un mot de passe en clair ou avec un hash rapide casse immédiatement les bonnes '
                        'pratiques de sécurité')],
 'Algorithmes et structures de données': [('Big O, Big Theta et Big Omega',
                                           'décrivent respectivement une borne supérieure, serrée ou inférieure de '
                                           'croissance asymptotique',
                                           "raisonner sur l'évolution d'un algorithme quand la taille d'entrée "
                                           'augmente',
                                           'confondre coût asymptotique et temps exact mesuré pour une petite entrée '
                                           'mène à de mauvaises conclusions'),
                                          ('Analyse asymptotique amortie',
                                           "étudie le coût moyen d'une séquence d'opérations plutôt qu'une seule "
                                           'opération isolée',
                                           'expliquer pourquoi un tableau dynamique reste efficace malgré des '
                                           'redimensionnements ponctuels',
                                           'se focaliser seulement sur le pire cas instantané masque parfois le '
                                           'comportement global réel'),
                                          ('Tableaux et listes chaînées',
                                           'offrent des compromis opposés entre accès indexé, localité mémoire et coût '
                                           "d'insertion",
                                           'choisir la structure selon la fréquence des accès aléatoires ou des '
                                           'insertions locales',
                                           'utiliser une liste chaînée pour des accès indexés intensifs dégrade les '
                                           'performances'),
                                          ('Piles, files et deques',
                                           'organisent les données selon LIFO, FIFO ou double extrémité',
                                           "modéliser une pile d'appels, une file d'attente ou une fenêtre glissante",
                                           'forcer une structure inadaptée complique inutilement les opérations '
                                           'dominantes'),
                                          ('Tables de hachage',
                                           "offrent des accès moyens rapides en s'appuyant sur une fonction de hachage "
                                           'et des buckets',
                                           'retrouver vite une valeur par clé dans un dictionnaire ou un ensemble',
                                           'une mauvaise fonction de hachage ou un facteur de charge excessif '
                                           'multiplie les collisions'),
                                          ('Tas binaire',
                                           'représente efficacement une file de priorité avec un ordre partiel '
                                           'parent-enfant',
                                           'extraire rapidement un minimum ou un maximum répété',
                                           "penser qu'un tas produit toujours une traversée triée complète est faux"),
                                          ('Arbres binaires de recherche',
                                           'maintiennent un ordre gauche-racine-droite facilitant recherche, insertion '
                                           'et suppression',
                                           'conserver un ensemble ordonné avec requêtes de prédécesseur ou successeur',
                                           "laisser l'arbre se dégénérer en liste fait perdre le bénéfice attendu"),
                                          ('AVL, Red-Black, B-Tree et Trie',
                                           "illustrent différentes stratégies d'équilibrage ou d'indexation "
                                           'hiérarchique',
                                           "choisir une structure selon l'accès mémoire, le disque ou la recherche par "
                                           'préfixe',
                                           "appliquer la même structure partout sans tenir compte du contexte d'usage "
                                           'est inefficace'),
                                          ('Graphes et représentations',
                                           "se modélisent souvent par listes d'adjacence ou matrices selon densité et "
                                           'opérations',
                                           'choisir une représentation compacte pour un graphe clairsemé ou rapide '
                                           'pour certains accès',
                                           'utiliser une matrice pour un très grand graphe sparse gaspille beaucoup de '
                                           'mémoire'),
                                          ('BFS et DFS',
                                           'parcourent un graphe ou un arbre en largeur ou en profondeur',
                                           'explorer des composantes, détecter des chemins ou ordonnancer une visite',
                                           'oublier une structure de visite sur un graphe cyclique peut provoquer des '
                                           'boucles infinies'),
                                          ('Dijkstra, Bellman-Ford et Floyd-Warshall',
                                           'résolvent des variantes de plus courts chemins selon les contraintes de '
                                           'poids et de portée',
                                           'choisir le bon algorithme selon présence de poids négatifs ou besoin tous '
                                           'couples',
                                           'utiliser Dijkstra sur des arêtes négatives produit des résultats '
                                           'potentiellement faux'),
                                          ('Kruskal, Prim et tri topologique',
                                           'couvrent arbre couvrant minimal et ordonnancement de graphes orientés '
                                           'acycliques',
                                           'connecter un graphe pondéré au moindre coût ou ordonner des dépendances',
                                           'appliquer un tri topologique à un graphe cyclique est impossible sans '
                                           'traiter le cycle'),
                                          ('Tris élémentaires et tris en O(n log n)',
                                           'montrent des compromis entre simplicité, stabilité, mémoire et performance',
                                           'sélectionner merge sort, quicksort ou insertion sort selon la taille et la '
                                           'nature des données',
                                           "oublier le pire cas d'un quicksort mal pivoté peut surprendre sur "
                                           'certaines entrées'),
                                          ('Recherche linéaire, binaire et ternaire',
                                           "diffèrent surtout par les préconditions et la réduction de l'espace de "
                                           'recherche',
                                           "tirer parti d'une collection triée avec une recherche logarithmique",
                                           "appliquer une recherche binaire sur des données non triées n'a pas de "
                                           'sens'),
                                          ('Récursivité, backtracking et mémoïsation',
                                           'décomposent un problème en sous-problèmes avec éventuellement mémorisation '
                                           'des résultats',
                                           'explorer un espace de solutions ou éviter des recalculs redondants',
                                           "omettre les cas de base ou l'élagage pertinent provoque vite une explosion "
                                           'combinatoire'),
                                          ('Programmation dynamique, glouton, KMP et bit manipulation',
                                           'rassemblent des techniques avancées de décision optimale, de traitement de '
                                           'chaînes et de calcul binaire',
                                           'résoudre efficacement un sac à dos, une LCS, une recherche de motif ou un '
                                           'test de bits',
                                           'appliquer une stratégie gloutonne sans preuve de validité peut donner une '
                                           'solution sous-optimale')]}

def _validate_topic_bank(category, topics):
    if len(topics) < 16:
        raise ValueError(
            f"La banque de thèmes de {category} doit contenir au moins 16 entrées pour générer les volumes attendus."
        )


def _sentence(text):
    text = text.strip()
    if not text.endswith((".", "?", "!")):
        text += "."
    return text


def _pick(pool, current_index, getter, offset=1, count=3):
    values = []
    for step in range(1, len(pool) + 1):
        candidate = getter(pool[(current_index + offset + step - 1) % len(pool)])
        if candidate not in values:
            values.append(candidate)
        if len(values) == count:
            return values
    raise ValueError("Impossible de construire trois distracteurs distincts.")


def _build_options(correct, distractors, seed):
    options = list(distractors[:3])
    answer_index = seed % 4
    options.insert(answer_index, correct)
    return options, "ABCD"[answer_index]


def _basic_questions(category, topics):
    generated = []
    for index, (concept, definition, application, advanced) in enumerate(topics):
        distractors = _pick(topics, index, lambda item: item[0])
        options, answer = _build_options(concept, distractors, index)
        generated.append(
            q(
                category,
                "Basique",
                f"Quel concept correspond le mieux à la description suivante ? {_sentence(definition)}",
                options,
                answer,
                _sentence(f"Il s'agit de {concept} : {definition}"),
            )
        )
    for index, (concept, definition, application, advanced) in enumerate(topics):
        distractors = _pick(topics, index, lambda item: _sentence(item[1]), offset=4)
        options, answer = _build_options(_sentence(definition), distractors, index + 17)
        generated.append(
            q(
                category,
                "Basique",
                f"Quelle affirmation décrit le mieux {concept} ?",
                options,
                answer,
                _sentence(f"{concept} se définit ainsi : {definition}"),
            )
        )
    return generated


def _intermediate_questions(category, topics):
    generated = []
    for index, (concept, definition, application, advanced) in enumerate(topics):
        distractors = _pick(topics, index, lambda item: _sentence(item[2]), offset=2)
        options, answer = _build_options(_sentence(application), distractors, index + 31)
        generated.append(
            q(
                category,
                "Intermédiaire",
                f"Dans quel contexte {concept} est-il le plus pertinent ?",
                options,
                answer,
                _sentence(f"{concept} est particulièrement pertinent lorsqu'il faut {application}"),
            )
        )
    for index, (concept, definition, application, advanced) in enumerate(topics):
        distractors = _pick(topics, index, lambda item: item[0], offset=5)
        options, answer = _build_options(concept, distractors, index + 53)
        generated.append(
            q(
                category,
                "Intermédiaire",
                f"Vous devez {application}. Quelle notion faut-il mobiliser en priorité ?",
                options,
                answer,
                _sentence(f"Le concept à mobiliser est {concept} car il sert à {application}"),
            )
        )
    for index, (concept, definition, application, advanced) in enumerate(topics[:5]):
        correct = _sentence(f"{concept} est surtout utile pour {application}")
        distractors = _pick(topics, index, lambda item: _sentence(f"{item[0]} est surtout utile pour {item[2]}"), offset=7)
        options, answer = _build_options(correct, distractors, index + 79)
        generated.append(
            q(
                category,
                "Intermédiaire",
                f"Quelle est la MEILLEURE réponse au sujet de {concept} ?",
                options,
                answer,
                _sentence(f"La réponse correcte relie {concept} à son usage principal : {application}"),
            )
        )
    return generated


def _advanced_questions(category, topics):
    generated = []
    for index, (concept, definition, application, advanced) in enumerate(topics):
        distractors = _pick(topics, index, lambda item: _sentence(item[3]), offset=3)
        options, answer = _build_options(_sentence(advanced), distractors, index + 101)
        generated.append(
            q(
                category,
                "Avancé",
                f"Quel énoncé traduit le mieux l'enjeu avancé lié à {concept} ?",
                options,
                answer,
                _sentence(f"Le point clé sur {concept} est que {advanced}"),
            )
        )
    for index, (concept, definition, application, advanced) in enumerate(topics[:5]):
        distractors = _pick(topics, index, lambda item: item[0], offset=9)
        options, answer = _build_options(concept, distractors, index + 137)
        generated.append(
            q(
                category,
                "Avancé",
                f"Quel concept est le plus directement concerné par le risque ou la nuance suivante ? {_sentence(advanced)}",
                options,
                answer,
                _sentence(f"Cette nuance renvoie à {concept} : {advanced}"),
            )
        )
    return generated


def _generated_questions_for_category(category):
    topics = TOPIC_BANKS[category]
    _validate_topic_bank(category, topics)
    return _basic_questions(category, topics) + _intermediate_questions(category, topics) + _advanced_questions(category, topics[:16])


def build_questions():
    questions = list(SEED_QUESTIONS)
    for category in CATEGORY_ORDER:
        questions.extend(_generated_questions_for_category(category))
    return questions


QUESTIONS = build_questions()

EXPECTED_TOTAL = len(CATEGORY_ORDER) * sum(DIFFICULTY_TARGETS.values())

if len(QUESTIONS) != EXPECTED_TOTAL:
    raise ValueError(f"Le jeu de questions doit contenir exactement {EXPECTED_TOTAL} QCM.")

category_counts = Counter(question["category"] for question in QUESTIONS)
difficulty_counts = Counter(question["difficulty"] for question in QUESTIONS)
pairs = Counter((question["category"], question["difficulty"]) for question in QUESTIONS)

expected_categories = set(CATEGORY_ORDER)
expected_difficulties = set(DIFFICULTY_ORDER)

if set(category_counts) != expected_categories:
    raise ValueError(
        f"Les catégories doivent correspondre exactement à l'ensemble attendu. "
        f"Obtenu={sorted(category_counts)}, attendu={sorted(expected_categories)}"
    )
if set(difficulty_counts) != expected_difficulties:
    raise ValueError(
        f"Les niveaux doivent correspondre exactement à l'ensemble attendu. "
        f"Obtenu={sorted(difficulty_counts)}, attendu={sorted(expected_difficulties)}"
    )
for category in CATEGORY_ORDER:
    if category_counts[category] < 100:
        raise ValueError(f"La catégorie {category} doit contenir au moins 100 questions.")
for difficulty, target in DIFFICULTY_TARGETS.items():
    for category in CATEGORY_ORDER:
        if pairs[(category, difficulty)] != target:
            raise ValueError(
                f"La catégorie {category} doit avoir {target} questions au niveau {difficulty}, "
                f"obtenu={pairs[(category, difficulty)]}"
            )

if len(set(category_counts.values())) != 1:
    raise ValueError("Les catégories doivent rester réparties équitablement.")

statements = [question["statement"] for question in QUESTIONS]
if len(statements) != len(set(statements)):
    raise ValueError("Les énoncés doivent rester uniques pour éviter les doublons exacts.")
