from collections import Counter


def q(category, difficulty, statement, options, answer, explanation):
    if len(options) != 4:
        raise ValueError(f"Chaque question doit avoir 4 choix: {statement}")
    if answer not in {"A", "B", "C", "D"}:
        raise ValueError(f"Réponse invalide pour: {statement}")
    return {
        "category": category,
        "difficulty": difficulty,
        "statement": statement,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }


QUESTIONS = [
    # Génie logiciel — Basique
    q("Génie logiciel", "Basique", "Quel modèle de cycle de vie suit généralement des phases séquentielles comme analyse, conception, développement et test ?", ["Scrum", "Waterfall", "Kanban", "DevOps"], "B", "Le modèle Waterfall organise le projet en étapes successives avec peu de retours en arrière."),
    q("Génie logiciel", "Basique", "Que représente UML ?", ["Un langage de modélisation unifié", "Un moteur d'exécution Java", "Une base de données relationnelle", "Un outil de versionnement"], "A", "UML signifie Unified Modeling Language et sert à modéliser la structure et le comportement d'un système."),
    q("Génie logiciel", "Basique", "Quel rôle principal joue Scrum Master dans Scrum ?", ["Déployer en production", "Supprimer les obstacles pour l'équipe", "Valider tout le code", "Écrire la documentation utilisateur"], "B", "Le Scrum Master facilite le processus Scrum et aide l'équipe à lever les blocages."),
    q("Génie logiciel", "Basique", "Quel diagramme UML est le plus utilisé pour représenter les classes et leurs relations ?", ["Diagramme de séquence", "Diagramme d'états", "Diagramme de classes", "Diagramme de déploiement"], "C", "Le diagramme de classes montre les attributs, méthodes et relations entre classes."),
    q("Génie logiciel", "Basique", "Quel principe SOLID recommande qu'une classe n'ait qu'une seule raison de changer ?", ["Single Responsibility Principle", "Open/Closed Principle", "Liskov Substitution Principle", "Dependency Inversion Principle"], "A", "Le SRP impose une responsabilité principale unique par classe."),
    q("Génie logiciel", "Basique", "Quel design pattern garantit qu'une classe ne possède qu'une seule instance ?", ["Factory", "Observer", "Singleton", "Strategy"], "C", "Singleton contrôle l'instanciation pour ne fournir qu'une unique instance."),
    # Génie logiciel — Intermédiaire
    q("Génie logiciel", "Intermédiaire", "Dans un diagramme de séquence UML, que représente une flèche entre deux objets ?", ["Une héritage", "Un message échangé", "Une clé étrangère", "Un package"], "B", "Le diagramme de séquence met en évidence les messages échangés dans l'ordre temporel."),
    q("Génie logiciel", "Intermédiaire", "Quel avantage principal apporte le pattern Factory ?", ["Empêcher les exceptions", "Centraliser la création d'objets", "Éviter les tests unitaires", "Réduire la mémoire JVM"], "B", "Factory encapsule l'instanciation et limite le couplage avec les implémentations concrètes."),
    q("Génie logiciel", "Intermédiaire", "Le TDD suit généralement quel enchaînement ?", ["Code, build, release", "Red, Green, Refactor", "Design, test, merge", "Plan, code, delete"], "B", "En TDD, on écrit d'abord un test en échec, on fait passer le test, puis on refactorise."),
    q("Génie logiciel", "Intermédiaire", "Quel énoncé décrit le mieux le principe Open/Closed ?", ["Une classe doit être fermée aux tests", "Un module doit être ouvert à l'extension et fermé à la modification", "Une API doit être fermée au réseau", "Une classe doit contenir un seul attribut public"], "B", "Le principe Open/Closed vise à ajouter des comportements sans modifier le code stable existant."),
    q("Génie logiciel", "Intermédiaire", "Que fait généralement le pattern Observer ?", ["Il crée des threads", "Il notifie plusieurs abonnés lors d'un changement d'état", "Il applique la normalisation 3NF", "Il remplace Git"], "B", "Observer met en place une relation sujet/observateurs avec notification automatique."),
    q("Génie logiciel", "Intermédiaire", "Quelle commande Git crée une nouvelle branche et s'y positionne immédiatement ?", ["git merge feature", "git checkout -b feature", "git reset --hard feature", "git branch -d feature"], "B", "`git checkout -b feature` crée la branche puis bascule dessus en une seule commande."),
    # Génie logiciel — Avancé
    q("Génie logiciel", "Avancé", "Quel risque principal apparaît lorsqu'une équipe applique Scrum sans définition claire de 'Done' ?", ["Le compilateur échoue systématiquement", "Les incréments deviennent difficiles à valider objectivement", "Les diagrammes UML deviennent obligatoires", "La branche main est supprimée"], "B", "Sans Definition of Done, la qualité et la complétude des livrables ne sont pas mesurables de manière cohérente."),
    q("Génie logiciel", "Avancé", "Lequel des cas suivants viole le plus directement le principe de substitution de Liskov ?", ["Une sous-classe ajoute une méthode privée", "Une sous-classe change le contrat attendu et lève une exception pour un cas auparavant valide", "Une sous-classe utilise un logger", "Une interface possède deux implémentations"], "B", "Une sous-classe ne doit pas casser les attentes fonctionnelles des clients du type parent."),
    q("Génie logiciel", "Avancé", "Quel bénéfice majeur apporte le pattern MVC dans une application riche ?", ["Il supprime le besoin de tests", "Il sépare les responsabilités entre données, interface et contrôle", "Il remplace une base de données relationnelle", "Il garantit le multithreading"], "B", "MVC améliore la maintenabilité en isolant modèle, vue et contrôleur."),
    q("Génie logiciel", "Avancé", "Quelle stratégie de branchement Git limite le plus les conflits de longue durée ?", ["Conserver des branches de fonctionnalités pendant plusieurs mois", "Intégrer fréquemment de petites branches de courte durée", "Commiter uniquement en fin de sprint", "Travailler uniquement sur des archives ZIP"], "B", "Des branches courtes et des intégrations fréquentes réduisent la divergence et les conflits."),
    q("Génie logiciel", "Avancé", "Dans un système fortement couplé, quel changement améliore le plus la testabilité ?", ["Ajouter des variables globales", "Introduire l'inversion de dépendance avec interfaces injectées", "Supprimer les exceptions", "Remplacer toutes les classes par une seule"], "B", "L'inversion de dépendance permet de substituer des implémentations de test et réduit le couplage."),
    q("Génie logiciel", "Avancé", "Quel indicateur traduit le mieux la valeur d'un test d'intégration ?", ["Il vérifie le style de code", "Il valide la collaboration entre composants réels ou proches du réel", "Il garantit l'absence de bugs UX", "Il remplace entièrement les tests unitaires"], "B", "Les tests d'intégration couvrent les interactions entre modules, couches ou services."),

    # Java — Basique
    q("Java", "Basique", "Quel concept POO permet à une classe fille de réutiliser le comportement d'une classe mère ?", ["Encapsulation", "Polymorphisme", "Héritage", "Sérialisation"], "C", "L'héritage permet à une classe de spécialiser une autre classe."),
    q("Java", "Basique", "Quelle collection Java n'autorise pas les doublons ?", ["List", "Set", "ArrayList", "LinkedList"], "B", "L'interface Set garantit l'unicité des éléments."),
    q("Java", "Basique", "À quoi sert un bloc try-catch ?", ["À définir une interface", "À gérer les exceptions", "À créer un thread", "À compiler plus vite"], "B", "Le bloc try-catch intercepte et traite des exceptions pendant l'exécution."),
    q("Java", "Basique", "Quelle classe est couramment utilisée pour représenter une paire clé-valeur ?", ["List", "Queue", "Map", "Stream"], "C", "Map associe une clé à une valeur."),
    q("Java", "Basique", "Quel mot-clé empêche la modification d'une variable locale après son initialisation ?", ["static", "const", "final", "volatile"], "C", "`final` interdit la réaffectation de la variable."),
    q("Java", "Basique", "Quelle méthode est appelée lorsqu'on démarre un thread via `new Thread(r).start()` ?", ["init()", "call()", "run()", "execute()"], "C", "`start()` crée un nouveau fil d'exécution qui invoque ensuite `run()`."),
    # Java — Intermédiaire
    q("Java", "Intermédiaire", "Quel avantage principal offrent les generics en Java ?", ["Ils remplacent la JVM", "Ils améliorent la sécurité de type à la compilation", "Ils permettent plusieurs héritages de classes", "Ils évitent tout casting à l'exécution même avec du code brut"], "B", "Les generics détectent des erreurs de type à la compilation et réduisent les casts explicites."),
    q("Java", "Intermédiaire", "Que retourne `stream().filter(x -> x > 10).count()` ?", ["Une liste filtrée", "Le nombre d'éléments satisfaisant la condition", "Le premier élément > 10", "Une Optional"], "B", "`count()` renvoie le nombre d'éléments du flux après filtrage."),
    q("Java", "Intermédiaire", "Quand utilise-t-on principalement `Optional` ?", ["Pour gérer explicitement une valeur potentiellement absente", "Pour remplacer toutes les collections", "Pour créer des threads daemon", "Pour définir une exception vérifiée"], "A", "Optional explicite l'absence éventuelle d'une valeur et limite certains `NullPointerException`."),
    q("Java", "Intermédiaire", "Quel type d'exception doit être déclarée ou capturée si elle est checked ?", ["RuntimeException", "NullPointerException", "IOException", "ArithmeticException"], "C", "`IOException` est une checked exception : elle doit être traitée ou déclarée."),
    q("Java", "Intermédiaire", "Quel composant JDBC représente généralement une requête SQL paramétrée précompilée ?", ["DriverManager", "PreparedStatement", "ResultSetMetaData", "SQLException"], "B", "PreparedStatement permet de paramétrer la requête et aide à prévenir l'injection SQL."),
    q("Java", "Intermédiaire", "Quelle différence majeure existe entre `ArrayList` et `LinkedList` ?", ["ArrayList interdit les null", "LinkedList optimise mieux les insertions/suppressions au milieu mais pas l'accès indexé", "ArrayList implémente Set", "LinkedList n'est pas une List"], "B", "ArrayList favorise l'accès indexé, alors que LinkedList favorise certaines insertions/suppressions."),
    # Java — Avancé
    q("Java", "Avancé", "Quel effet a le mot-clé `volatile` sur un champ partagé entre threads ?", ["Il rend toutes les opérations atomiques", "Il garantit surtout la visibilité des écritures entre threads", "Il empêche tout blocage`,", "Il remplace `synchronized` dans tous les cas"], "B", "`volatile` garantit la visibilité mémoire, mais pas l'atomicité d'opérations composées comme `count++`."),
    q("Java", "Avancé", "Pourquoi préférer `ExecutorService` à la création manuelle de nombreux threads ?", ["Parce qu'il empêche les exceptions", "Parce qu'il gère un pool de threads et le cycle de vie des tâches", "Parce qu'il compile le code plus vite", "Parce qu'il remplace les interfaces fonctionnelles"], "B", "ExecutorService mutualise les threads et facilite la gestion, la limitation et l'arrêt des tâches."),
    q("Java", "Avancé", "Quel est le rôle principal du garbage collector de la JVM ?", ["Optimiser les index SQL", "Libérer automatiquement la mémoire des objets non référencés", "Empêcher les exceptions vérifiées", "Compiler les fichiers XML"], "B", "Le garbage collector récupère la mémoire des objets qui ne sont plus atteignables."),
    q("Java", "Avancé", "Dans une hiérarchie immuable bien conçue, quel bénéfice obtient-on principalement ?", ["Les objets deviennent plus faciles à partager entre threads", "Les objets ne peuvent plus être sérialisés", "Le polymorphisme disparaît", "La JVM n'utilise plus de heap"], "A", "L'immuabilité réduit les effets de bord et facilite l'usage concurrent."),
    q("Java", "Avancé", "Quel problème peut survenir avec un `parallelStream()` mal utilisé ?", ["La disparition des exceptions compilées", "Une baisse de performances due au surcoût parallèle ou à des effets de bord non sûrs", "L'impossibilité d'utiliser des lambdas", "La suppression des doublons"], "B", "Le parallélisme n'est pas toujours bénéfique et peut poser des problèmes avec des traitements stateful."),
    q("Java", "Avancé", "Pourquoi un `PreparedStatement` est-il plus sûr qu'une concaténation de chaînes pour une requête SQL ?", ["Il chiffre automatiquement les données", "Il sépare la structure SQL des paramètres utilisateurs", "Il supprime les transactions", "Il transforme toutes les colonnes en index"], "B", "Les paramètres sont liés séparément, ce qui réduit fortement le risque d'injection SQL."),

    # Spring — Basique
    q("Spring / Spring Boot", "Basique", "Que signifie IoC dans Spring ?", ["Input of Code", "Inversion of Control", "Instance of Component", "Injection of Cache"], "B", "L'Inversion of Control délègue la création et la gestion des objets au conteneur Spring."),
    q("Spring / Spring Boot", "Basique", "Quelle annotation déclare couramment un composant de service métier ?", ["@Service", "@Table", "@BeanFactory", "@InjectableController"], "A", "`@Service` marque une classe de service gérée par Spring."),
    q("Spring / Spring Boot", "Basique", "Quelle annotation est utilisée sur une classe exposant des endpoints REST ?", ["@Repository", "@RestController", "@Entity", "@ConfigurationPropertiesScanOnly"], "B", "`@RestController` combine `@Controller` et `@ResponseBody` pour des API REST."),
    q("Spring / Spring Boot", "Basique", "Que permet principalement l'injection de dépendances ?", ["Augmenter la taille du JAR", "Réduire le couplage entre composants", "Remplacer la JVM", "Créer des jointures SQL"], "B", "L'injection de dépendances facilite le remplacement et le test des collaborations."),
    q("Spring / Spring Boot", "Basique", "Quel composant est généralement chargé de l'accès aux données ?", ["@Repository", "@ControllerAdvice", "@RestController", "@Scheduled"], "A", "`@Repository` identifie les composants de persistance."),
    q("Spring / Spring Boot", "Basique", "Quel outil Spring Boot expose des endpoints de supervision comme `/actuator/health` ?", ["Spring Batch", "Actuator", "Feign", "Thymeleaf"], "B", "Spring Boot Actuator fournit des informations de santé, métriques et supervision."),
    # Spring — Intermédiaire
    q("Spring / Spring Boot", "Intermédiaire", "Quelle différence majeure existe entre `@Component` et `@Bean` ?", ["Aucune dans tous les cas", "`@Component` scanne une classe, `@Bean` déclare un objet via une méthode de configuration", "`@Bean` ne fonctionne pas avec Spring Boot", "`@Component` crée uniquement des repositories"], "B", "`@Component` repose sur le classpath scanning alors que `@Bean` enregistre le retour d'une méthode de configuration."),
    q("Spring / Spring Boot", "Intermédiaire", "Quel avantage offre `@Autowired` sur constructeur dans une classe de service ?", ["Il masque les dépendances", "Il favorise des dépendances explicites et des tests plus simples", "Il évite toutes les annotations", "Il remplace JPA"], "B", "L'injection par constructeur rend les dépendances visibles et favorise l'immuabilité."),
    q("Spring / Spring Boot", "Intermédiaire", "À quoi sert typiquement une interface qui étend `JpaRepository<User, Long>` ?", ["À compiler le JDK", "À fournir des opérations CRUD et de pagination sur l'entité User", "À créer un contrôleur MVC", "À sécuriser les mots de passe"], "B", "Spring Data JPA génère des implémentations pour les accès CRUD courants."),
    q("Spring / Spring Boot", "Intermédiaire", "Que fait `@RequestBody` dans Spring MVC ?", ["Il lit le corps HTTP et le convertit en objet Java", "Il chiffre automatiquement la requête", "Il ajoute une transaction SQL", "Il force une vue JSP"], "A", "`@RequestBody` désérialise le contenu de la requête vers un type Java."),
    q("Spring / Spring Boot", "Intermédiaire", "Quel mécanisme Spring Security est souvent utilisé pour stocker les rôles d'un utilisateur authentifié ?", ["SecurityContext", "JDBC URL", "BeanFactory", "DispatcherServlet"], "A", "Le `SecurityContext` contient l'authentification courante et ses autorités."),
    q("Spring / Spring Boot", "Intermédiaire", "Quel est le rôle du `DispatcherServlet` dans Spring MVC ?", ["Exécuter le garbage collector", "Recevoir les requêtes web et déléguer aux bons contrôleurs", "Créer des tables SQL", "Scanner les dépendances Maven"], "B", "`DispatcherServlet` est le front controller de Spring MVC."),
    # Spring — Avancé
    q("Spring / Spring Boot", "Avancé", "Pourquoi limiter l'injection par champ (`field injection`) dans une application Spring moderne ?", ["Parce qu'elle interdit JPA", "Parce qu'elle complique les tests et masque les dépendances", "Parce qu'elle désactive Actuator", "Parce qu'elle change le port HTTP"], "B", "L'injection par constructeur est plus explicite et plus simple à tester."),
    q("Spring / Spring Boot", "Avancé", "Quel bénéfice principal apporte `@Transactional` sur une méthode de service métier ?", ["Créer automatiquement des index", "Garantir une unité de travail cohérente avec commit/rollback", "Remplacer les contrôleurs REST", "Éviter toute exception Java"], "B", "Une transaction regroupe les opérations et permet un rollback en cas d'échec."),
    q("Spring / Spring Boot", "Avancé", "Pourquoi exposer tous les endpoints Actuator en production peut-il être risqué ?", ["Parce que Spring ne démarre plus", "Parce que certaines informations d'exploitation peuvent être sensibles", "Parce que JSON devient invalide", "Parce que JPA ne fonctionne plus"], "B", "Les endpoints peuvent révéler des métriques, mappings ou détails internes utiles à un attaquant."),
    q("Spring / Spring Boot", "Avancé", "Dans Spring Data JPA, quel problème peut apparaître lorsqu'on sérialise directement une entité avec relations LAZY hors transaction ?", ["Un code 201 automatique", "Une LazyInitializationException", "Une compilation plus lente", "Une perte du bean principal"], "B", "Une relation LAZY non initialisée ne peut pas être chargée une fois la session fermée."),
    q("Spring / Spring Boot", "Avancé", "Quel choix améliore le plus la robustesse d'une API REST Spring ?", ["Retourner systématiquement 200 OK", "Centraliser la gestion d'erreurs avec `@ControllerAdvice` et des statuts cohérents", "Utiliser uniquement des contrôleurs statiques", "Désactiver la validation"], "B", "Une gestion centralisée des erreurs rend l'API plus cohérente et prédictible."),
    q("Spring / Spring Boot", "Avancé", "Pourquoi externaliser la configuration via `application.yml` et variables d'environnement ?", ["Pour lier fortement le code à une machine", "Pour séparer configuration et code selon l'environnement", "Pour empêcher les tests", "Pour supprimer le besoin d'annotations"], "B", "Cela facilite le déploiement sur plusieurs environnements sans modifier le code source."),

    # SQL — Basique
    q("SQL / Bases de données", "Basique", "Quel ordre SQL sert à créer une table ?", ["SELECT", "INSERT", "CREATE TABLE", "UPDATE"], "C", "`CREATE TABLE` fait partie du DDL et crée une nouvelle table."),
    q("SQL / Bases de données", "Basique", "Quelle clause permet de filtrer des lignes avant agrégation ?", ["HAVING", "ORDER BY", "WHERE", "GROUP BY"], "C", "`WHERE` filtre les lignes sources avant les regroupements."),
    q("SQL / Bases de données", "Basique", "Quelle jointure retourne uniquement les lignes correspondantes dans les deux tables ?", ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN"], "C", "`INNER JOIN` conserve seulement les correspondances présentes dans les deux côtés."),
    q("SQL / Bases de données", "Basique", "Quelle commande SQL ajoute une nouvelle ligne dans une table ?", ["INSERT", "ALTER", "DROP", "TRUNCATE"], "A", "`INSERT` ajoute des enregistrements."),
    q("SQL / Bases de données", "Basique", "Quelle fonction d'agrégation compte le nombre de lignes ?", ["SUM", "COUNT", "AVG", "MIN"], "B", "`COUNT` retourne le nombre de lignes ou de valeurs non nulles selon l'expression."),
    q("SQL / Bases de données", "Basique", "Que signifie le 'C' de l'acronyme ACID ?", ["Cache", "Consistency", "Column", "Cursor"], "B", "ACID signifie Atomicity, Consistency, Isolation, Durability."),
    # SQL — Intermédiaire
    q("SQL / Bases de données", "Intermédiaire", "Quelle clause filtre les groupes après un `GROUP BY` ?", ["WHERE", "HAVING", "LIMIT", "VALUES"], "B", "`HAVING` s'applique aux groupes déjà agrégés."),
    q("SQL / Bases de données", "Intermédiaire", "Quel est l'effet principal d'un index sur une colonne fréquemment recherchée ?", ["Il supprime les doublons automatiquement", "Il peut accélérer les lectures ciblées mais a un coût en écriture", "Il remplace les clés étrangères", "Il garantit la 3NF"], "B", "Un index améliore souvent les recherches, au prix de stockage et de maintenance supplémentaires."),
    q("SQL / Bases de données", "Intermédiaire", "Dans une relation 1-N, où place-t-on généralement la clé étrangère ?", ["Dans la table du côté N", "Dans la table du côté 1", "Dans une vue", "Dans toutes les tables"], "A", "La clé étrangère se trouve en général dans la table qui porte plusieurs occurrences liées au parent."),
    q("SQL / Bases de données", "Intermédiaire", "Quelle forme normale élimine principalement les dépendances partielles sur une clé composée ?", ["1NF", "2NF", "3NF", "BCNF"], "B", "La 2NF traite les dépendances partielles par rapport aux clés candidates composées."),
    q("SQL / Bases de données", "Intermédiaire", "Que retourne une sous-requête utilisée avec `IN` ?", ["Obligatoirement une seule ligne", "Un ensemble de valeurs comparables", "Une transaction active", "Un index bitmap"], "B", "`IN` compare une valeur à un ensemble retourné par la sous-requête."),
    q("SQL / Bases de données", "Intermédiaire", "Quel langage est spécifiquement associé à Oracle pour les blocs procéduraux ?", ["T-SQL", "PL/SQL", "JPQL", "XPath"], "B", "PL/SQL étend SQL avec des structures procédurales côté Oracle."),
    # SQL — Avancé
    q("SQL / Bases de données", "Avancé", "Pourquoi une transaction doit-elle être courte en environnement concurrent ?", ["Pour changer le type des colonnes", "Pour réduire le temps de verrouillage et la contention", "Pour supprimer la normalisation", "Pour éviter les clés primaires"], "B", "Des transactions courtes libèrent plus vite les ressources et limitent les blocages."),
    q("SQL / Bases de données", "Avancé", "Quel problème une mauvaise isolation peut-elle provoquer ?", ["Dirty read", "Compilation du schéma", "Suppression des index", "Encodage UTF-8"], "A", "Une isolation trop faible peut permettre de lire des données non validées : dirty reads."),
    q("SQL / Bases de données", "Avancé", "Quand une table est en 3NF, quel objectif a été atteint ?", ["Toutes les colonnes sont indexées", "Les dépendances transitives non clés ont été supprimées", "Il n'existe plus de valeurs nulles", "Toutes les requêtes sont optimisées"], "B", "La 3NF vise à éliminer les dépendances transitives qui nuisent à la cohérence."),
    q("SQL / Bases de données", "Avancé", "Quel intérêt majeur apporte BCNF par rapport à 3NF ?", ["Elle supprime les transactions", "Elle renforce la contrainte sur les déterminants pour réduire certaines anomalies restantes", "Elle remplace MERISE", "Elle interdit les jointures"], "B", "BCNF est plus stricte que la 3NF lorsque des dépendances fonctionnelles particulières subsistent."),
    q("SQL / Bases de données", "Avancé", "Dans MERISE, quel modèle décrit surtout les données de manière conceptuelle, indépendante de l'implémentation ?", ["MCD", "MPD", "MCT", "JPA"], "A", "Le MCD (modèle conceptuel de données) décrit entités, associations et cardinalités."),
    q("SQL / Bases de données", "Avancé", "Quelle requête est généralement la plus sûre contre l'injection lorsqu'elle provient d'une application ?", ["Une concaténation de chaînes SQL", "Une requête préparée paramétrée", "Une requête copiée depuis un log", "Une vue matérialisée"], "B", "Les paramètres liés dans une requête préparée évitent d'interpréter l'entrée comme du code SQL."),

    # Web — Basique
    q("Développement Web", "Basique", "Quel langage structure le contenu d'une page web ?", ["CSS", "HTML", "SQL", "JSON"], "B", "HTML décrit la structure sémantique des pages web."),
    q("Développement Web", "Basique", "Quel langage est principalement utilisé pour la mise en forme d'une page web ?", ["CSS", "Java", "HTTP", "REST"], "A", "CSS contrôle la présentation visuelle : couleurs, marges, disposition, etc."),
    q("Développement Web", "Basique", "Quel format léger est couramment utilisé pour échanger des données dans une API REST ?", ["PDF", "JSON", "BMP", "CSV binaire"], "B", "JSON est très utilisé pour les échanges de données entre client et serveur."),
    q("Développement Web", "Basique", "Quel code HTTP signifie généralement 'Not Found' ?", ["200", "201", "404", "500"], "C", "404 indique qu'aucune ressource ne correspond à l'URL demandée."),
    q("Développement Web", "Basique", "Quelle méthode HTTP est généralement utilisée pour récupérer une ressource sans la modifier ?", ["POST", "PATCH", "GET", "DELETE"], "C", "GET sert à lire une ressource et doit être sûre du point de vue sémantique."),
    q("Développement Web", "Basique", "Quel risque de sécurité correspond à l'injection de script dans une page vue par d'autres utilisateurs ?", ["CSRF", "XSS", "Deadlock", "Race condition"], "B", "Le XSS permet d'exécuter du JavaScript malveillant dans le navigateur de la victime."),
    # Web — Intermédiaire
    q("Développement Web", "Intermédiaire", "Quel en-tête HTTP indique souvent le type de contenu renvoyé ?", ["Authorization", "Content-Type", "Cache-Control", "Origin"], "B", "`Content-Type` décrit le média renvoyé, par exemple `application/json`."),
    q("Développement Web", "Intermédiaire", "Quelle différence décrit le mieux REST ?", ["REST impose XML uniquement", "REST repose sur des ressources identifiées et des verbes HTTP standard", "REST remplace TCP", "REST fonctionne sans HTTP"], "B", "REST organise les échanges autour de ressources et d'opérations standardisées."),
    q("Développement Web", "Intermédiaire", "Quel mécanisme aide à limiter les attaques CSRF sur un formulaire authentifié ?", ["Un token CSRF côté serveur", "Une variable globale JavaScript", "Un commentaire HTML", "Une jointure SQL"], "A", "Un token imprévisible validé par le serveur réduit les requêtes forgées inter-sites."),
    q("Développement Web", "Intermédiaire", "Pourquoi valider aussi côté serveur des données déjà validées côté client ?", ["Parce que le navigateur garantit déjà tout", "Parce que la validation côté client peut être contournée", "Pour supprimer le besoin d'API", "Pour éviter l'UTF-8"], "B", "Le client n'est pas digne de confiance : les contrôles serveur restent indispensables."),
    q("Développement Web", "Intermédiaire", "Quel sélecteur CSS cible un élément avec l'identifiant `menu` ?", [".menu", "#menu", "menu[]", "@menu"], "B", "Le caractère `#` cible un identifiant en CSS."),
    q("Développement Web", "Intermédiaire", "Quel statut HTTP convient généralement le mieux après la création réussie d'une ressource par POST ?", ["200 OK", "201 Created", "204 No Content", "304 Not Modified"], "B", "201 indique qu'une nouvelle ressource a été créée avec succès."),
    # Web — Avancé
    q("Développement Web", "Avancé", "Quelle mesure réduit le plus le risque XSS persistant dans une application web ?", ["Augmenter la RAM du serveur", "Échapper/encoder les données non fiables selon le contexte de rendu", "Masquer les erreurs SQL", "Utiliser uniquement GET"], "B", "L'encodage contextuel des sorties et la sanitation ciblée sont des défenses clés contre le XSS."),
    q("Développement Web", "Avancé", "Pourquoi une API REST ne devrait-elle pas exposer directement les messages d'erreur internes d'une base de données ?", ["Parce qu'ils peuvent révéler des détails sensibles facilitant l'attaque", "Parce qu'ils ralentissent CSS", "Parce qu'ils empêchent JSON", "Parce qu'ils désactivent HTTP/2"], "A", "Les messages internes peuvent divulguer schéma, requêtes ou stack traces utiles à un attaquant."),
    q("Développement Web", "Avancé", "Quel attribut de cookie aide à limiter l'accès du JavaScript au cookie de session ?", ["Secure", "HttpOnly", "Path=/api", "Expires"], "B", "`HttpOnly` empêche l'accès au cookie via `document.cookie`, limitant certains impacts XSS."),
    q("Développement Web", "Avancé", "Quel scénario décrit le mieux une injection SQL ?", ["Un script CSS modifie la couleur du site", "Une entrée utilisateur modifie la structure d'une requête SQL concaténée", "Un navigateur met en cache une image", "Un token JWT expire"], "B", "L'injection SQL survient lorsque l'entrée utilisateur est interprétée comme du code SQL."),
    q("Développement Web", "Avancé", "Quelle architecture front/back améliore souvent la maintenabilité d'une application web complexe ?", ["Mélanger requêtes SQL, HTML et logique métier dans le même fichier", "Séparer clairement présentation, logique client et API serveur", "Supprimer tout cache HTTP", "Utiliser uniquement des variables globales"], "B", "La séparation des couches réduit le couplage et simplifie l'évolution."),
    q("Développement Web", "Avancé", "Pour une API publique, quel mécanisme renforce le plus la robustesse face aux abus ?", ["Désactiver les logs", "Mettre en place authentification, autorisation et rate limiting", "Répondre 200 à toutes les requêtes", "Supprimer TLS"], "B", "L'authentification et la limitation de débit réduisent les usages abusifs et malveillants."),

    # Algo — Basique
    q("Algorithmes et structures de données", "Basique", "Que mesure principalement la notation Big O ?", ["La couleur du code", "L'ordre de croissance du coût d'un algorithme", "Le nombre exact d'octets utilisés par la JVM", "La version du compilateur"], "B", "Big O exprime l'évolution asymptotique du temps ou de l'espace selon la taille d'entrée."),
    q("Algorithmes et structures de données", "Basique", "Quel algorithme de recherche nécessite généralement un tableau trié ?", ["Recherche linéaire", "Recherche binaire", "Parcours en profondeur", "Tri par insertion"], "B", "La recherche binaire exploite l'ordre des éléments pour diviser l'intervalle en deux."),
    q("Algorithmes et structures de données", "Basique", "Quelle structure suit le principe FIFO ?", ["Pile", "File", "Arbre binaire", "Tas"], "B", "Une file traite en premier l'élément arrivé en premier."),
    q("Algorithmes et structures de données", "Basique", "Quelle structure suit le principe LIFO ?", ["Pile", "File", "Graphe", "Table de hachage"], "A", "Une pile retourne en premier le dernier élément ajouté."),
    q("Algorithmes et structures de données", "Basique", "Dans une liste chaînée simple, chaque nœud contient généralement :", ["Seulement une clé primaire", "Une valeur et un pointeur vers le suivant", "Un tableau trié complet", "Deux hash maps"], "B", "Un nœud stocke une donnée et une référence vers le nœud suivant."),
    q("Algorithmes et structures de données", "Basique", "Quel parcours visite d'abord la racine, puis le sous-arbre gauche, puis le sous-arbre droit ?", ["Infixe", "Postfixe", "Préfixe", "Largeur"], "C", "Le parcours préfixe suit l'ordre racine-gauche-droite."),
    # Algo — Intermédiaire
    q("Algorithmes et structures de données", "Intermédiaire", "Quelle est la complexité temporelle moyenne d'une recherche binaire ?", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "B", "À chaque étape, la recherche binaire réduit de moitié l'espace de recherche."),
    q("Algorithmes et structures de données", "Intermédiaire", "Quel tri a une complexité moyenne de O(n log n) et repose sur la stratégie diviser pour régner ?", ["Bubble sort", "Merge sort", "Selection sort", "Insertion sort"], "B", "Merge sort divise le tableau puis fusionne les sous-tableaux triés."),
    q("Algorithmes et structures de données", "Intermédiaire", "Dans un arbre binaire de recherche, quelle propriété est vraie ?", ["Tous les nœuds ont deux enfants", "Les valeurs du sous-arbre gauche sont inférieures à la racine", "Les feuilles sont chaînées entre elles", "La racine est toujours la médiane exacte"], "B", "Un BST impose un ordre relatif gauche < racine < droite."),
    q("Algorithmes et structures de données", "Intermédiaire", "Quel algorithme parcourt typiquement un graphe niveau par niveau ?", ["DFS", "BFS", "Dijkstra sans file", "Merge sort"], "B", "Le Breadth-First Search visite les voisins par couches successives."),
    q("Algorithmes et structures de données", "Intermédiaire", "Quand une fonction récursive doit-elle impérativement définir un cas de base ?", ["Seulement en Java", "Toujours, pour garantir l'arrêt", "Jamais si elle utilise une liste", "Uniquement pour les graphes"], "B", "Sans cas de base, la récursion risque de ne jamais s'arrêter."),
    q("Algorithmes et structures de données", "Intermédiaire", "Quel coût a généralement l'accès au ième élément d'une liste chaînée simple ?", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], "C", "Il faut parcourir séquentiellement les nœuds jusqu'à la position demandée."),
    # Algo — Avancé
    q("Algorithmes et structures de données", "Avancé", "Quel risque principal présente une implémentation récursive profonde sans optimisation de pile ?", ["Une collision d'index SQL", "Un dépassement de pile (`stack overflow`)", "Une perte du garbage collector", "Un deadlock réseau"], "B", "Chaque appel consomme de la pile ; une profondeur excessive peut provoquer un débordement."),
    q("Algorithmes et structures de données", "Avancé", "Dans quel cas un `HashMap` se rapproche-t-il le plus d'une recherche en O(n) ?", ["Quand la fonction de hachage répartit bien les clés", "Quand de nombreuses collisions dégradent les buckets", "Quand les clés sont immuables", "Quand la table est vide"], "B", "Des collisions excessives peuvent dégrader les performances d'accès."),
    q("Algorithmes et structures de données", "Avancé", "Quel avantage offre un arbre équilibré par rapport à un arbre binaire de recherche dégénéré ?", ["Il garantit des opérations proches de O(log n)", "Il supprime la mémoire utilisée", "Il interdit les doublons dans tous les cas", "Il remplace BFS"], "A", "L'équilibrage limite la hauteur et préserve de bonnes performances."),
    q("Algorithmes et structures de données", "Avancé", "Pourquoi Dijkstra ne convient-il pas tel quel avec des poids négatifs ?", ["Parce qu'il nécessite un graphe complet", "Parce que son hypothèse de relaxation progressive n'est plus valide", "Parce qu'il utilise trop peu de mémoire", "Parce qu'il trie en O(n²)"], "B", "Des arêtes négatives peuvent invalider le choix glouton de Dijkstra."),
    q("Algorithmes et structures de données", "Avancé", "Quel critère guide principalement le choix entre tableau dynamique et liste chaînée ?", ["La couleur de l'IDE", "Les profils d'accès, d'insertion et les contraintes mémoire", "Le nom des variables", "Le système d'exploitation uniquement"], "B", "Le bon choix dépend des opérations dominantes et des compromis mémoire/performance."),
    q("Algorithmes et structures de données", "Avancé", "Quelle structure est la plus adaptée pour implémenter efficacement une file de priorité classique ?", ["Un tas binaire", "Une liste simplement chaînée non triée", "Un tableau 2D", "Une pile"], "A", "Le tas binaire offre de bonnes complexités pour insertion et extraction du minimum/maximum."),
]


if len(QUESTIONS) < 100:
    raise ValueError("Le jeu de questions doit contenir au moins 100 QCM.")

category_counts = Counter(question["category"] for question in QUESTIONS)
difficulty_counts = Counter(question["difficulty"] for question in QUESTIONS)
pairs = Counter((question["category"], question["difficulty"]) for question in QUESTIONS)

expected_categories = {
    "Génie logiciel",
    "Java",
    "Spring / Spring Boot",
    "SQL / Bases de données",
    "Développement Web",
    "Algorithmes et structures de données",
}
expected_difficulties = {"Basique", "Intermédiaire", "Avancé"}

if set(category_counts) != expected_categories:
    raise ValueError("Les catégories attendues ne sont pas toutes présentes.")
if set(difficulty_counts) != expected_difficulties:
    raise ValueError("Les niveaux attendus ne sont pas tous présents.")
if len(set(category_counts.values())) != 1:
    raise ValueError("Les catégories doivent être réparties équitablement.")
if len(set(pairs.values())) != 1:
    raise ValueError("Chaque catégorie doit avoir le même nombre de questions par niveau.")
